
create table csx_analyse_fr_cas_credential_item_detail_mi(
`biz_id`                                bigint              COMMENT    '业务主键id',
`credential_no`                         string              COMMENT    '凭证编号',
`province_name`                         string              COMMENT    '省区',
`city_name`                             string              COMMENT    '城市',
`division_name`                         string              COMMENT    '部类',
`create_time`                           timestamp           COMMENT    '创建时间',
`wms_order_time`                        timestamp           COMMENT    '订单时间',
`credential_item_posting_time`          timestamp           COMMENT    '记账时间',
`company_code`                          string              COMMENT    '公司代码',
`company_name`                          string              COMMENT    '公司名称',
`location_code`                         string              COMMENT    'DC编码',
`location_name`                         string              COMMENT    'DC名称',
`reservoir_area_code`                   string              COMMENT    '库区编码',
`reservoir_area_name`                   string              COMMENT    '库区名称',
`purchase_group_code`                   string              COMMENT    '采购组编码',
`purchase_group_name`                   string              COMMENT    '采购组名称',
`goods_code`                            string              COMMENT    '商品编码',
`goods_name`                            string              COMMENT    '商品名称',
`classify_large_code`                   string              COMMENT    '管理大类编码',
`classify_large_name`                   string              COMMENT    '管理大类名称',
`classify_middle_code`                  string              COMMENT    '管理中类编码',
`classify_middle_name`                  string              COMMENT    '管理中类名称',
`classify_small_code`                   string              COMMENT    '管理小类编码',
`classify_small_name`                   string              COMMENT    '管理小类名称',
`move_type_code`                        string              COMMENT    '移动类型编码',
`move_type_name`                        string              COMMENT    '移动类型名称',
`wms_biz_type_code`                     string              COMMENT    '报损类型',
`wms_biz_type_name`                     string              COMMENT    '报损名称',
`cost_center_code`                      string              COMMENT    '成本中心编码',
`cost_center_name`                      string              COMMENT    '成本中心名称',
`reservoir_area_attribute`              string              COMMENT    '库区属性',
`pd_no_qty`                             decimal(16,4)       COMMENT    '盘点未过账数量',
`pd_no_amt_no_tax`                      decimal(16,4)       COMMENT    '盘点未过账不含税金额',
`pd_no_amt`                             decimal(16,4)       COMMENT    '盘点未过账含税金额',
`pd_yes_qty`                            decimal(16,4)       COMMENT    '盘点过账数量',
`pd_yes_amt_no_tax`                     decimal(16,4)       COMMENT    '盘点过账不含税金额',
`pd_yes_amt`                            decimal(16,4)       COMMENT    '盘点过账含税金额',
`bs_qty`                                decimal(16,4)       COMMENT    '报损数量',
`bs_amt_no_tax`                         decimal(16,4)       COMMENT    '报损不含税金额',
`bs_amt`                                decimal(16,4)       COMMENT    '报损含税金额',
`biz_type`                              string              COMMENT    '盘点报损类型',
`pd_type`                               string              COMMENT    '盘点类型',
`sdt_month`                             string              COMMENT    '日期分区'
) COMMENT '盘点报损明细表'
PARTITIONED BY (sdt string COMMENT '日期分区')
STORED AS PARQUET;



CREATE TABLE `report_csx_analyse_fr_cas_credential_item_detail_mi` (
`id` 							 bigint(20)     	  NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         bigint(20)          NOT NULL DEFAULT '0' COMMENT    '业务主键id',
`credential_no`                  varchar(32)         NOT NULL DEFAULT '' COMMENT    '凭证编号',
`province_name`                  varchar(16)         NOT NULL DEFAULT '' COMMENT    '省区',
`city_name`                      varchar(64)         NOT NULL DEFAULT '' COMMENT    '城市',
`division_name`                  varchar(16)         NOT NULL DEFAULT '' COMMENT    '部类',
`create_time`                    datetime            DEFAULT NULL  COMMENT    '创建时间',
`wms_order_time`                 datetime            DEFAULT NULL  COMMENT    '订单时间',
`credential_item_posting_time`   datetime            DEFAULT NULL  COMMENT    '记账时间',
`company_code`                   varchar(16)         DEFAULT NULL  COMMENT    '公司代码',
`company_name`                   varchar(64)         DEFAULT NULL  COMMENT    '公司名称',
`location_code`                  varchar(16)         NOT NULL DEFAULT '' COMMENT    'DC编码',
`location_name`                  varchar(64)         DEFAULT NULL  COMMENT    'DC名称',
`reservoir_area_code`            varchar(16)         DEFAULT NULL  COMMENT    '库区编码',
`reservoir_area_name`            varchar(64)         DEFAULT NULL  COMMENT    '库区名称',
`purchase_group_code`            varchar(16)         DEFAULT NULL  COMMENT    '采购组编码',
`purchase_group_name`            varchar(64)         DEFAULT NULL  COMMENT    '采购组名称',
`goods_code`                     varchar(16)         DEFAULT NULL  COMMENT    '商品编码',
`goods_name`                     varchar(64)         DEFAULT NULL  COMMENT    '商品名称',
`classify_large_code`            varchar(16)         DEFAULT NULL  COMMENT    '管理大类编码',
`classify_large_name`            varchar(64)         DEFAULT NULL  COMMENT    '管理大类名称',
`classify_middle_code`           varchar(16)         DEFAULT NULL  COMMENT    '管理中类编码',
`classify_middle_name`           varchar(64)         DEFAULT NULL  COMMENT    '管理中类名称',
`classify_small_code`            varchar(16)         DEFAULT NULL  COMMENT    '管理小类编码',
`classify_small_name`            varchar(64)         DEFAULT NULL  COMMENT    '管理小类名称',
`move_type_code`                 varchar(16)         DEFAULT NULL  COMMENT    '移动类型编码',
`move_type_name`                 varchar(64)         DEFAULT NULL  COMMENT    '移动类型名称',
`wms_biz_type_code`              varchar(16)         DEFAULT NULL  COMMENT    '报损类型',
`wms_biz_type_name`              varchar(64)         DEFAULT NULL  COMMENT    '报损名称',
`cost_center_code`               varchar(16)         DEFAULT NULL  COMMENT    '成本中心编码',
`cost_center_name`               varchar(64)         DEFAULT NULL  COMMENT    '成本中心名称',
`reservoir_area_attribute`       varchar(16)         DEFAULT NULL  COMMENT    '库区属性',
`pd_no_qty`                      decimal(16,4)       DEFAULT NULL  COMMENT    '盘点未过账数量',
`pd_no_amt_no_tax`               decimal(16,4)       DEFAULT NULL  COMMENT    '盘点未过账不含税金额',
`pd_no_amt`                      decimal(16,4)       DEFAULT NULL  COMMENT    '盘点未过账含税金额',
`pd_yes_qty`                     decimal(16,4)       DEFAULT NULL  COMMENT    '盘点过账数量',
`pd_yes_amt_no_tax`              decimal(16,4)       DEFAULT NULL  COMMENT    '盘点过账不含税金额',
`pd_yes_amt`                     decimal(16,4)       DEFAULT NULL  COMMENT    '盘点过账含税金额',
`bs_qty`                         decimal(16,4)       DEFAULT NULL  COMMENT    '报损数量',
`bs_amt_no_tax`                  decimal(16,4)       DEFAULT NULL  COMMENT    '报损不含税金额',
`bs_amt`                         decimal(16,4)       DEFAULT NULL  COMMENT    '报损含税金额',
`biz_type`                       varchar(16)         NOT NULL DEFAULT '' COMMENT    '盘点报损类型',
`pd_type`                        varchar(16)         NOT NULL DEFAULT '' COMMENT    '盘点类型',
`sdt_month`                      varchar(16)         NOT NULL DEFAULT '' COMMENT    '日期分区',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='盘点报损明细表';

