CREATE TABLE `report_csx_analyse_wms_requisition_order_detail_di` (
`id` 							 bigint(20)     	  NOT NULL AUTO_INCREMENT COMMENT '主键',
`order_code`                     varchar(32)         DEFAULT NULL  COMMENT    '领用单号',
`dc_code`                        varchar(32)         DEFAULT NULL  COMMENT    '仓库编号',
`dc_name`                        varchar(32)         DEFAULT NULL  COMMENT    '仓库名称',
`shipper_code`                   varchar(32)         DEFAULT NULL  COMMENT    '货主编号',
`shipper_name`                   varchar(32)         DEFAULT NULL  COMMENT    '货主名称',
`goods_code`                     varchar(32)         DEFAULT NULL  COMMENT    '商品编号',
`goods_bar_code`                 varchar(32)         DEFAULT NULL  COMMENT    '商品条码',
`goods_name`                     varchar(64)         DEFAULT NULL  COMMENT    '商品名称',
`unit_name`                      varchar(16)         DEFAULT NULL  COMMENT    '单位',
`price`                          decimal(12,4)       DEFAULT NULL  COMMENT    '领用商品单价',
`requisition_qty`                decimal(12,3)       DEFAULT NULL  COMMENT    '领用数量',
`requisition_amt`                decimal(12,4)       DEFAULT NULL  COMMENT    '领用商品总金额',
`price_no_tax`                   decimal(12,4)       DEFAULT NULL  COMMENT    '不含税领用商品单价',
`requisition_amt_no_tax`         decimal(12,4)       DEFAULT NULL  COMMENT    '不含税领用商品总金额',
`requisition_type_code`          varchar(32)         DEFAULT NULL  COMMENT    '领用类型编号',
`requisition_type_name`          varchar(64)         DEFAULT NULL  COMMENT    '领用类型名称',
`cost_center_code`               varchar(32)         DEFAULT NULL  COMMENT    '成本中心编号',
`cost_center_name`               varchar(64)         DEFAULT NULL  COMMENT    '成本中心名称',
`status`                         int                 DEFAULT NULL  COMMENT    '状态 0-初始1-已执行 2-已关闭',
`remark`                         varchar(128)        DEFAULT NULL  COMMENT    '备注',
`create_time`                    datetime            DEFAULT NULL  COMMENT    '创建时间',
`create_by`                      varchar(16)         DEFAULT NULL  COMMENT    '创建者',
`update_time`                    datetime            DEFAULT NULL  COMMENT    '更新时间',
`update_by`                      varchar(16)         DEFAULT NULL  COMMENT    '更新者',
`excute_time`                    datetime            DEFAULT NULL  COMMENT    '执行时间',
`excute_by`                      varchar(16)         DEFAULT NULL  COMMENT    '执行人',
`production_date`                datetime            DEFAULT NULL  COMMENT    '生产日期',
`expiry_date`                    datetime            DEFAULT NULL  COMMENT    '有效期至',
`store_location_code`            varchar(16)         DEFAULT NULL  COMMENT    '储位编码',
`approval_status`                int                 DEFAULT NULL  COMMENT    '审批状态',
`approve_remarks`                varchar(64)         DEFAULT NULL  COMMENT    '审批意见',
`user_id`                        bigint              DEFAULT NULL  COMMENT    '发起审批人ID',
`stock_attribute_code`           varchar(16)         DEFAULT NULL  COMMENT    '库存属性编码',
`purchase_group_code`            varchar(16)         DEFAULT NULL  COMMENT    '采购组(课组)编码',
`purchase_group_name`            varchar(32)         DEFAULT NULL  COMMENT    '采购组(课组)名称',
`category_large_code`            varchar(16)         DEFAULT NULL  COMMENT    '大类编号',
`category_large_name`            varchar(32)         DEFAULT NULL  COMMENT    '大类名称',
`category_middle_code`           varchar(16)         DEFAULT NULL  COMMENT    '中类编号',
`category_middle_name`           varchar(32)         DEFAULT NULL  COMMENT    '中类名称',
`category_small_code`            varchar(16)         DEFAULT NULL  COMMENT    '小类编号',
`category_small_name`            varchar(32)         DEFAULT NULL  COMMENT    '小类名称',
`area_code`                      varchar(16)         DEFAULT NULL  COMMENT    '大区编码',
`area_name`                      varchar(32)         DEFAULT NULL  COMMENT    '大区名称',
`province_code`                  varchar(16)         DEFAULT NULL  COMMENT    '省区编码',
`province_name`                  varchar(32)         DEFAULT NULL  COMMENT    '省区名称',
`city_code`                      varchar(16)         DEFAULT NULL  COMMENT    '城市编码',
`city_name`                      varchar(32)         DEFAULT NULL  COMMENT    '城市名称',
`first_code`                     varchar(16)         DEFAULT NULL  COMMENT    '一级部门编码',
`first_name`                     varchar(32)         DEFAULT NULL  COMMENT    '一级部门名称',
`second_code`                    varchar(16)         DEFAULT NULL  COMMENT    '二级部门编码',
`second_name`                    varchar(32)         DEFAULT NULL  COMMENT    '二级部门名称',
`excute_date`                    varchar(16)         DEFAULT NULL  COMMENT    '执行日期',
`sdt`                            varchar(16)         DEFAULT NULL  COMMENT    '日期分区',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='领用明细表';