CREATE TABLE `report_fr_sell_exceptions_monitor_m_df` (
`id` 							 bigint(20)     	  NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(64)          DEFAULT NULL COMMENT    '业务主键',
`performance_region_code`        varchar(64)          DEFAULT NULL COMMENT    '大区编码',
`performance_region_name`        varchar(64)          DEFAULT NULL COMMENT    '大区名称',
`performance_province_code`      varchar(64)          DEFAULT NULL COMMENT    '省区编码',
`performance_province_name`      varchar(64)          DEFAULT NULL COMMENT    '省区名称',
`performance_city_code`          varchar(64)          DEFAULT NULL COMMENT    '城市编码',
`performance_city_name`          varchar(64)          DEFAULT NULL COMMENT    '城市名称',
`out_no`                         varchar(64)          DEFAULT NULL COMMENT    '外部单号',
`dc_code`                        varchar(64)          DEFAULT NULL COMMENT    '库存dc 编码',
`dc_name`                        varchar(64)          DEFAULT NULL COMMENT    '库存dc 名称',
`shop_code`                      varchar(64)          DEFAULT NULL COMMENT    '门店编码',
`shop_name`                      varchar(64)          DEFAULT NULL COMMENT    '门店名称',
`ex_big_class`                   int                  DEFAULT NULL COMMENT    '异常大类',
`ex_big_class_name`              varchar(64)          DEFAULT NULL COMMENT    '异常大类名称',
`ex_small_class`                 int                  DEFAULT NULL COMMENT    '异常小类',
`ex_small_class_name`            varchar(64)          DEFAULT NULL COMMENT    '异常小类名称',
`status`                         int                  DEFAULT NULL COMMENT    '状态',
`status_name`                    varchar(64)          DEFAULT NULL COMMENT    '状态名称',
`supplier_code`                  varchar(64)          DEFAULT NULL COMMENT    '供应商编码',
`remarks`                        varchar(64)          DEFAULT NULL COMMENT    '补充说明',
`inner_order_no`                 varchar(64)          DEFAULT NULL COMMENT    '拆单号，生单异常没有拆单号',
`created_time`                   datetime             DEFAULT NULL COMMENT    '申请时间(创建时间)',
`updated_time`                   datetime             DEFAULT NULL COMMENT    '更新时间',
`created_by`                     varchar(64)          DEFAULT NULL COMMENT    '申请人',
`updated_by`                     varchar(64)          DEFAULT NULL COMMENT    '更新人',
`update_time`                    datetime             DEFAULT NULL COMMENT    '更新时间',
`create_time`                    datetime             DEFAULT NULL COMMENT    '创建时间',
`ex_small_class_union`           varchar(64)          DEFAULT NULL COMMENT    '异常小类合并',
`residence_time_hour`            decimal(26,6)        DEFAULT NULL COMMENT    '停留时长-小时',
`residence_time_day`             decimal(26,6)        DEFAULT NULL COMMENT    '停留时长-天',
`sdt`                     		 varchar(64)          DEFAULT NULL COMMENT    '统计日期',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商超-异常监控';


-- delete from data_analysis_prd.report_fr_sell_exceptions_monitor_m_df where sdt>=date_format(date_sub(now(), interval 1 day), '%Y%m%d')
