CREATE TABLE IF NOT EXISTS csx_tmp.csx_tmp_dwd_bbc_wshop_work_order_goods_real_2tidb(
  `id` STRING COMMENT '联合主键（工单号&商品编码）',
  `work_code` STRING COMMENT '工单号',
  `feedback_channel_code` INT COMMENT '反馈渠道 0-400 1-省区 2-线上',
  `user_telephone` STRING COMMENT '手机号',
  `user_name` STRING COMMENT '联系人',
  `customer_code` STRING COMMENT '客户号',
  `customer_name` STRING COMMENT '客户名称',
  `performance_region_code` STRING COMMENT '业绩大区编码',
  `performance_region_name` STRING COMMENT '业绩大区名称',
  `performance_province_code` STRING COMMENT '业绩省区编码',
  `performance_province_name` STRING COMMENT '业绩省区名称',
  `performance_city_code` STRING COMMENT '业绩城市编码',
  `performance_city_name` STRING COMMENT '业绩城市名称',
  `credit_type_code` STRING COMMENT '授信类型编码',
  `credit_type_name` STRING COMMENT '授信类型名称',
  `operation_mode_code` INT COMMENT '经营方式编码：0-自营 1-联营(非京东) 2-京东 3-永辉生活 4-永辉线下购',
  `operation_mode_name` STRING COMMENT '经营方式名称',
  `delivery_type_code` INT COMMENT '配送类型编码：1-配送 2-直送 3-自提 4-直通 11-同城配送 12-快递配送 13-一件代发 14-即时达',
  `delivery_type_name` STRING COMMENT '配送类型名称',
  `inventory_dc_code` STRING COMMENT '出库工厂',
  `sign_company_code` STRING COMMENT '签约公司',
  `site_code` STRING COMMENT '站点编码',
  `site_name` STRING COMMENT '站点名称',
  `first_type_name` STRING COMMENT '一级业务类型',
  `second_type_name` STRING COMMENT '二级业务类型',
  `third_type_name` STRING COMMENT '三级业务类型',
  `order_code` STRING COMMENT '订单号',
  `order_key` STRING COMMENT '申请订单号',
  `goods_type_code` INT COMMENT '商品销售类型',
  `goods_code` STRING COMMENT '商品编号',
  `goods_name` STRING COMMENT '商品名称',
  `classify_large_code` STRING COMMENT '管理大类编号',
  `classify_large_name` STRING COMMENT '管理大类名称',
  `classify_middle_code` STRING COMMENT '管理中类编号',
  `classify_middle_name` STRING COMMENT '管理中类名称',
  `classify_small_code` STRING COMMENT '管理小类编号',
  `classify_small_name` STRING COMMENT '管理小类名称',
  `supplier_code` STRING COMMENT '供应商编号',
  `supplier_name` STRING COMMENT '供应商名称',
  `purchase_manager_user_number` STRING COMMENT '采购负责人工号',
  `purchase_manager_user_name` STRING COMMENT '采购负责人姓名',
  `qty` DECIMAL (12, 4) COMMENT '数量',
  `price` DECIMAL (10, 2) COMMENT '单价',
  `amt` DECIMAL (10, 2) COMMENT '金额',
  `remark` STRING COMMENT '备注',
  `need_notice` INT COMMENT '是否需要通知 0-否 1-是',
  `need_call_back` INT COMMENT '是否需要通知回调 0-否 1-是',
  `notice_remark` STRING COMMENT '通知内容',
  `notice_curator_id` STRING COMMENT '通知负责人id',
  `notice_curator_name` STRING COMMENT '通知负责人姓名',
  `process_status` INT COMMENT '处理状态 0-未处理 1-已完成',
  `inventory_dc` STRING COMMENT '出库工厂',
  `business_owner` STRING COMMENT '业态归属',
  `end_time` TIMESTAMP COMMENT '完结时间',
  `create_time` TIMESTAMP COMMENT '创建时间',
  `create_by` STRING COMMENT '创建人',
  `update_time` TIMESTAMP COMMENT '更新时间',
  `update_by` STRING COMMENT '更新人',
  `sdt`       STRING COMMENT '创建日期 yyyyMMdd',
  `basic_performance_region_code`   STRING COMMENT '主数据业绩归属大区编码',
  `basic_performance_region_name`   STRING COMMENT '主数据业绩归属大区名称',
  `basic_performance_province_code` STRING COMMENT '主数据业绩归属省区编码',
  `basic_performance_province_name` STRING COMMENT '主数据业绩归属省区名称',
  `basic_performance_city_code`     STRING COMMENT '主数据业绩归属城市编码',
  `basic_performance_city_name`     STRING COMMENT '主数据业绩归属城市名称'
) COMMENT '业务工单表' STORED AS PARQUET;









    SELECT
      COUNT(DISTINCT work_code) AS complaintCount,
      COUNT(DISTINCT customer_code) AS complaintCustomerCount,
      COUNT(DISTINCT order_code, goods_code) AS complaintSkuCount
    FROM
      dwd_bbc_wshop_work_order_goods_real
    WHERE
      sdt BETWEEN '20251001' AND '20251011'
      and (
        basic_performance_city_code in (
          '211001',
          '210001',
          '209001',
          '206003',
          '206002',
          '206001',
          '205001',
          '204001',
          '203001',
          '202001',
          '201001',
          '200001',
          '124003',
          '124002',
          '124001',
          '123004',
          '123003',
          '123002',
          '123001',
          '122001',
          '121001',
          '119001',
          '117001',
          '113001',
          '112006',
          '112005',
          '112004',
          '112003',
          '112002',
          '112001',
          '111001',
          '110001',
          '109001',
          '108001',
          '107001',
          '106001',
          '105001',
          '104009',
          '104008',
          '104007',
          '104006',
          '104005',
          '104004',
          '104003',
          '104002',
          '102004',
          '102002',
          '102001',
          '101001',
          '100001',
          '112007',
          '212001',
          '213001',
          '110003',
          '214001',
          '122002',
          '212002',
          '101002',
          '124005',
          '212003',
          '124004'
        )
        OR basic_performance_city_code = ''
      )
 
