--hive 客户提成宽表
drop table if exists csx_tmp.report_sss_r_m_crm_customer_commission_detail;
create table csx_tmp.report_sss_r_m_crm_customer_commission_detail(
`biz_id`                         string              COMMENT    '业务主键',
`region_code_customer`           string              COMMENT    '客户大区编码',
`region_name_customer`           string              COMMENT    '客户大区名称',
`province_code_customer`         string              COMMENT    '客户省份编码',
`province_name_customer`         string              COMMENT    '客户省份名称',
`city_group_code_customer`       string              COMMENT    '客户城市组编码',
`city_group_name_customer`       string              COMMENT    '客户城市组名称',
`region_code_sales`              string              COMMENT    '销售员大区编码',
`region_name_sales`              string              COMMENT    '销售员大区名称',
`province_code_sales`            string              COMMENT    '销售员省份编码',
`province_name_sales`            string              COMMENT    '销售员省份名称',
`city_group_code_sales`          string              COMMENT    '销售员城市组编码',
`city_group_name_sales`          string              COMMENT    '销售员城市组名称',
`region_code_rp_service`         string              COMMENT    '日配服务管家大区编码',
`region_name_rp_service`         string              COMMENT    '日配服务管家大区名称',
`province_code_rp_service`       string              COMMENT    '日配服务管家省份编码',
`province_name_rp_service`       string              COMMENT    '日配服务管家省份名称',
`city_group_code_rp_service`     string              COMMENT    '日配服务管家城市组编码',
`city_group_name_rp_service`     string              COMMENT    '日配服务管家城市组名称',
`region_code_fl_service`         string              COMMENT    '福利服务管家大区编码',
`region_name_fl_service`         string              COMMENT    '福利服务管家大区名称',
`province_code_fl_service`       string              COMMENT    '福利服务管家省份编码',
`province_name_fl_service`       string              COMMENT    '福利服务管家省份名称',
`city_group_code_fl_service`     string              COMMENT    '福利服务管家城市组编码',
`city_group_name_fl_service`     string              COMMENT    '福利服务管家城市组名称',
`region_code_bbc_service`        string              COMMENT    'BBC服务管家大区编码',
`region_name_bbc_service`        string              COMMENT    'BBC服务管家大区名称',
`province_code_bbc_service`      string              COMMENT    'BBC服务管家省份编码',
`province_name_bbc_service`      string              COMMENT    'BBC服务管家省份名称',
`city_group_code_bbc_service`    string              COMMENT    'BBC服务管家城市组编码',
`city_group_name_bbc_service`    string              COMMENT    'BBC服务管家城市组名称',
`yearmonth`                     string               COMMENT    '年月',
`customer_id`                    string              COMMENT    '客户id',
`customer_no`                    string              COMMENT    '客户编码',
`customer_name`                  string              COMMENT    '客户名称',
`sales_id`                       string              COMMENT    '销售员id',
`work_no`                        string              COMMENT    '销售员工号',
`sales_name`                     string              COMMENT    '销售员名称',
`rp_service_user_id`             string              COMMENT    '日配服务管家id',
`rp_service_user_work_no`        string              COMMENT    '日配服务管家工号',
`rp_service_user_name`           string              COMMENT    '日配服务管家名称',
`fl_service_user_id`             string              COMMENT    '福利服务管家id',
`fl_service_user_work_no`        string              COMMENT    '福利服务管家工号',
`fl_service_user_name`           string              COMMENT    '福利服务管家名称',
`bbc_service_user_id`            string              COMMENT    'BBC服务管家id',
`bbc_service_user_work_no`       string              COMMENT    'BBC服务管家工号',
`bbc_service_user_name`          string              COMMENT    'BBC服务管家名称',
`sales_value`                    decimal(20,6)       COMMENT    '销售额',
`rp_sales_value`                 decimal(20,6)       COMMENT    '日配销售额',
`fl_sales_value`                 decimal(20,6)       COMMENT    '福利销售额',
`bbc_sales_value`                decimal(20,6)       COMMENT    'BBC销售额',
`rp_bbc_sales_value`             decimal(20,6)       COMMENT    '日配&BBC销售额',
`profit`                         decimal(20,6)       COMMENT    '定价毛利额',
`rp_profit`                      decimal(20,6)       COMMENT    '日配定价毛利额',
`fl_profit`                      decimal(20,6)       COMMENT    '福利定价毛利额',
`bbc_profit`                     decimal(20,6)       COMMENT    'BBC定价毛利额',
`rp_bbc_profit`                  decimal(20,6)       COMMENT    '日配&BBC定价毛利额',
`prorate`                        decimal(20,6)       COMMENT    '定价毛利率',
`rp_prorate`                     decimal(20,6)       COMMENT    '日配定价毛利率',
`fl_prorate`                     decimal(20,6)       COMMENT    '福利定价毛利率',
`bbc_prorate`                    decimal(20,6)       COMMENT    'BBC定价毛利率',
`rp_bbc_prorate`                 decimal(20,6)       COMMENT    '日配&BBC定价毛利率',
`sales_prorate`                  decimal(20,6)       COMMENT    '销售员定价毛利率',
`sales_rp_prorate`               decimal(20,6)       COMMENT    '销售员日配定价毛利率',
`sales_fl_prorate`               decimal(20,6)       COMMENT    '销售员福利定价毛利率',
`sales_bbc_prorate`              decimal(20,6)       COMMENT    '销售员BBC定价毛利率',
`sales_rp_bbc_prorate`           decimal(20,6)       COMMENT    '销售员日配&BBC定价毛利率',
`salary_rp_sales_value`          decimal(20,6)       COMMENT    '奖金包_日配销售额',
`salary_rp_profit`               decimal(20,6)       COMMENT    '奖金包_日配定价毛利率',
`salary_fl_sales_value`          decimal(20,6)       COMMENT    '奖金包_福利销售额',
`salary_fl_profit`               decimal(20,6)       COMMENT    '奖金包_福利定价毛利率',
`salary_bbc_sales_value`         decimal(20,6)       COMMENT    '奖金包_BBC销售额',
`salary_bbc_profit`              decimal(20,6)       COMMENT    '奖金包_BBC定价毛利率',
`salary_sales_value`             decimal(20,6)       COMMENT    '奖金包_销售额',
`salary_profit`                  decimal(20,6)       COMMENT    '奖金包_定价毛利额',
`receivable_amount`              decimal(20,6)       COMMENT    '应收金额',
`overdue_amount`                 decimal(20,6)       COMMENT    '逾期金额',
`rp_sales_sale_fp_rate`          decimal(20,6)       COMMENT    '销售员_日配销售额分配比例',
`rp_sales_profit_fp_rate`        decimal(20,6)       COMMENT    '销售员_日配毛利额分配比例',
`fl_sales_sale_fp_rate`          decimal(20,6)       COMMENT    '销售员_福利销售额分配比例',
`fl_sales_profit_fp_rate`        decimal(20,6)       COMMENT    '销售员_福利毛利额分配比例',
`bbc_sales_sale_fp_rate`         decimal(20,6)       COMMENT    '销售员_BBC销售额分配比例',
`bbc_sales_profit_fp_rate`       decimal(20,6)       COMMENT    '销售员_BBC毛利额分配比例',
`rp_service_user_sale_fp_rate`   decimal(20,6)       COMMENT    '服务管家_日配销售额分配比例',
`rp_service_user_profit_fp_rate` decimal(20,6)       COMMENT    '服务管家_日配毛利额分配比例',
`fl_service_user_sale_fp_rate`   decimal(20,6)       COMMENT    '服务管家_福利销售额分配比例',
`fl_service_user_profit_fp_rate` decimal(20,6)       COMMENT    '服务管家_福利毛利额分配比例',
`bbc_service_user_sale_fp_rate`  decimal(20,6)       COMMENT    '服务管家_BBC销售额分配比例',
`bbc_service_user_profit_fp_rate`decimal(20,6)       COMMENT    '服务管家_BBC毛利额分配比例',
`sales_over_rate`                decimal(20,6)       COMMENT    '销售员逾期系数',
`rp_service_user_over_rate`      decimal(20,6)       COMMENT    '日配服务管家逾期系数',
`fl_service_user_over_rate`      decimal(20,6)       COMMENT    '福利服务管家逾期系数',
`bbc_service_user_over_rate`     decimal(20,6)       COMMENT    'BBC服务管家逾期系数',
`rp_service_receivable_amount`   decimal(20,6)       COMMENT    '日配服务管家应收金额',
`rp_service_overdue_amount`      decimal(20,6)       COMMENT    '日配服务管家逾期金额',
`fl_service_receivable_amount`   decimal(20,6)       COMMENT    '福利服务管家应收金额',
`fl_service_overdue_amount`      decimal(20,6)       COMMENT    '福利服务管家逾期金额',
`bbc_service_receivable_amount`  decimal(20,6)       COMMENT    'BBC服务管家应收金额',
`bbc_service_overdue_amount`     decimal(20,6)       COMMENT    'BBC服务管家逾期金额',
`sales_sales_value_ytd`          decimal(20,6)       COMMENT    '销售员年至今销售额',
`sales_rp_bbc_sales_value_ytd`   decimal(20,6)       COMMENT    '销售员年至今日配BBC销售额',
`sales_fl_sales_value_ytd`       decimal(20,6)       COMMENT    '销售员年至今福利销售额',
`tc_rp_sales_value_sales`        decimal(20,6)       COMMENT    '提成_销售员_日配销售额',
`tc_rp_profit_sales`             decimal(20,6)       COMMENT    '提成_销售员_日配毛利额',
`tc_fl_sales_value_sales`        decimal(20,6)       COMMENT    '提成_销售员_福利销售额',
`tc_fl_profit_sales`             decimal(20,6)       COMMENT    '提成_销售员_福利毛利额',
`tc_bbc_sales_value_sales`       decimal(20,6)       COMMENT    '提成_销售员_bbc销售额',
`tc_bbc_profit_sales`            decimal(20,6)       COMMENT    '提成_销售员_bbc毛利额',
`tc_sales`                       decimal(20,6)       COMMENT    '提成_销售员',
`tc_rp_sales_value_service`      decimal(20,6)       COMMENT    '提成_日配服务管家_日配销售额',
`tc_rp_profit_service`           decimal(20,6)       COMMENT    '提成_日配服务管家_日配毛利额',
`tc_rp_service`                  decimal(20,6)       COMMENT    '提成_日配服务管家',
`tc_fl_sales_value_service`      decimal(20,6)       COMMENT    '提成_福利服务管家_福利销售额',
`tc_fl_profit_service`           decimal(20,6)       COMMENT    '提成_福利服务管家_福利毛利额',
`tc_fl_service`                  decimal(20,6)       COMMENT    '提成_福利服务管家',
`tc_bbc_sales_value_service`     decimal(20,6)       COMMENT    '提成_BBC服务管家_BBC销售额',
`tc_bbc_profit_service`          decimal(20,6)       COMMENT    '提成_BBC服务管家_BBC毛利额',
`tc_bbc_service`                 decimal(20,6)       COMMENT    '提成_BBC服务管家',
`create_by`                      string              COMMENT    '创建人',
`create_time`                    timestamp           COMMENT    '同步时间',
`update_time`                    timestamp           COMMENT    '更新时间'

) COMMENT '客户提成宽表'
PARTITIONED BY (sdt string COMMENT '日期分区')
STORED AS TEXTFILE;


--mysql 客户提成宽表
CREATE TABLE `report_sss_r_m_crm_customer_commission_detail` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(64)          NOT NULL  COMMENT    '业务主键',
`region_code_customer`           varchar(64)          DEFAULT NULL  COMMENT    '客户大区编码',
`region_name_customer`           varchar(64)          DEFAULT NULL  COMMENT    '客户大区名称',
`province_code_customer`         varchar(64)          DEFAULT NULL  COMMENT    '客户省份编码',
`province_name_customer`         varchar(64)          DEFAULT NULL  COMMENT    '客户省份名称',
`city_group_code_customer`       varchar(64)          DEFAULT NULL  COMMENT    '客户城市组编码',
`city_group_name_customer`       varchar(64)          DEFAULT NULL  COMMENT    '客户城市组名称',
`region_code_sales`              varchar(64)          DEFAULT NULL  COMMENT    '销售员大区编码',
`region_name_sales`              varchar(64)          DEFAULT NULL  COMMENT    '销售员大区名称',
`province_code_sales`            varchar(64)          DEFAULT NULL  COMMENT    '销售员省份编码',
`province_name_sales`            varchar(64)          DEFAULT NULL  COMMENT    '销售员省份名称',
`city_group_code_sales`          varchar(64)          DEFAULT NULL  COMMENT    '销售员城市组编码',
`city_group_name_sales`          varchar(64)          DEFAULT NULL  COMMENT    '销售员城市组名称',
`region_code_rp_service`         varchar(64)          DEFAULT NULL  COMMENT    '日配服务管家大区编码',
`region_name_rp_service`         varchar(64)          DEFAULT NULL  COMMENT    '日配服务管家大区名称',
`province_code_rp_service`       varchar(64)          DEFAULT NULL  COMMENT    '日配服务管家省份编码',
`province_name_rp_service`       varchar(64)          DEFAULT NULL  COMMENT    '日配服务管家省份名称',
`city_group_code_rp_service`     varchar(64)          DEFAULT NULL  COMMENT    '日配服务管家城市组编码',
`city_group_name_rp_service`     varchar(64)          DEFAULT NULL  COMMENT    '日配服务管家城市组名称',
`region_code_fl_service`         varchar(64)          DEFAULT NULL  COMMENT    '福利服务管家大区编码',
`region_name_fl_service`         varchar(64)          DEFAULT NULL  COMMENT    '福利服务管家大区名称',
`province_code_fl_service`       varchar(64)          DEFAULT NULL  COMMENT    '福利服务管家省份编码',
`province_name_fl_service`       varchar(64)          DEFAULT NULL  COMMENT    '福利服务管家省份名称',
`city_group_code_fl_service`     varchar(64)          DEFAULT NULL  COMMENT    '福利服务管家城市组编码',
`city_group_name_fl_service`     varchar(64)          DEFAULT NULL  COMMENT    '福利服务管家城市组名称',
`region_code_bbc_service`        varchar(64)          DEFAULT NULL  COMMENT    'BBC服务管家大区编码',
`region_name_bbc_service`        varchar(64)          DEFAULT NULL  COMMENT    'BBC服务管家大区名称',
`province_code_bbc_service`      varchar(64)          DEFAULT NULL  COMMENT    'BBC服务管家省份编码',
`province_name_bbc_service`      varchar(64)          DEFAULT NULL  COMMENT    'BBC服务管家省份名称',
`city_group_code_bbc_service`    varchar(64)          DEFAULT NULL  COMMENT    'BBC服务管家城市组编码',
`city_group_name_bbc_service`    varchar(64)          DEFAULT NULL  COMMENT    'BBC服务管家城市组名称',
`yearmonth`                      varchar(64)          DEFAULT NULL  COMMENT    '年月',
`customer_id`                    varchar(64)          DEFAULT NULL  COMMENT    '客户id',
`customer_no`                    varchar(64)          DEFAULT NULL  COMMENT    '客户编码',
`customer_name`                  varchar(64)          DEFAULT NULL  COMMENT    '客户名称',
`sales_id`                       varchar(64)          DEFAULT NULL  COMMENT    '销售员id',
`work_no`                        varchar(64)          DEFAULT NULL  COMMENT    '销售员工号',
`sales_name`                     varchar(64)          DEFAULT NULL  COMMENT    '销售员名称',
`rp_service_user_id`             varchar(64)          DEFAULT NULL  COMMENT    '日配服务管家id',
`rp_service_user_work_no`        varchar(64)          DEFAULT NULL  COMMENT    '日配服务管家工号',
`rp_service_user_name`           varchar(64)          DEFAULT NULL  COMMENT    '日配服务管家名称',
`fl_service_user_id`             varchar(64)          DEFAULT NULL  COMMENT    '福利服务管家id',
`fl_service_user_work_no`        varchar(64)          DEFAULT NULL  COMMENT    '福利服务管家工号',
`fl_service_user_name`           varchar(64)          DEFAULT NULL  COMMENT    '福利服务管家名称',
`bbc_service_user_id`            varchar(64)          DEFAULT NULL  COMMENT    'BBC服务管家id',
`bbc_service_user_work_no`       varchar(64)          DEFAULT NULL  COMMENT    'BBC服务管家工号',
`bbc_service_user_name`          varchar(64)          DEFAULT NULL  COMMENT    'BBC服务管家名称',
`sales_value`                    decimal(20,6)        DEFAULT NULL  COMMENT    '销售额',
`rp_sales_value`                 decimal(20,6)        DEFAULT NULL  COMMENT    '日配销售额',
`fl_sales_value`                 decimal(20,6)        DEFAULT NULL  COMMENT    '福利销售额',
`bbc_sales_value`                decimal(20,6)        DEFAULT NULL  COMMENT    'BBC销售额',
`rp_bbc_sales_value`             decimal(20,6)        DEFAULT NULL  COMMENT    '日配&BBC销售额',
`profit`                         decimal(20,6)        DEFAULT NULL  COMMENT    '定价毛利额',
`rp_profit`                      decimal(20,6)        DEFAULT NULL  COMMENT    '日配定价毛利额',
`fl_profit`                      decimal(20,6)        DEFAULT NULL  COMMENT    '福利定价毛利额',
`bbc_profit`                     decimal(20,6)        DEFAULT NULL  COMMENT    'BBC定价毛利额',
`rp_bbc_profit`                  decimal(20,6)        DEFAULT NULL  COMMENT    '日配&BBC定价毛利额',
`prorate`                        decimal(20,6)        DEFAULT NULL  COMMENT    '定价毛利率',
`rp_prorate`                     decimal(20,6)        DEFAULT NULL  COMMENT    '日配定价毛利率',
`fl_prorate`                     decimal(20,6)        DEFAULT NULL  COMMENT    '福利定价毛利率',
`bbc_prorate`                    decimal(20,6)        DEFAULT NULL  COMMENT    'BBC定价毛利率',
`rp_bbc_prorate`                 decimal(20,6)        DEFAULT NULL  COMMENT    '日配&BBC定价毛利率',
`sales_prorate`                  decimal(20,6)        DEFAULT NULL  COMMENT    '销售员定价毛利率',
`sales_rp_prorate`               decimal(20,6)        DEFAULT NULL  COMMENT    '销售员日配定价毛利率',
`sales_fl_prorate`               decimal(20,6)        DEFAULT NULL  COMMENT    '销售员福利定价毛利率',
`sales_bbc_prorate`              decimal(20,6)        DEFAULT NULL  COMMENT    '销售员BBC定价毛利率',
`sales_rp_bbc_prorate`           decimal(20,6)        DEFAULT NULL  COMMENT    '销售员日配&BBC定价毛利率',
`salary_rp_sales_value`          decimal(20,6)        DEFAULT NULL  COMMENT    '奖金包_日配销售额',
`salary_rp_profit`               decimal(20,6)        DEFAULT NULL  COMMENT    '奖金包_日配定价毛利率',
`salary_fl_sales_value`          decimal(20,6)        DEFAULT NULL  COMMENT    '奖金包_福利销售额',
`salary_fl_profit`               decimal(20,6)        DEFAULT NULL  COMMENT    '奖金包_福利定价毛利率',
`salary_bbc_sales_value`         decimal(20,6)        DEFAULT NULL  COMMENT    '奖金包_BBC销售额',
`salary_bbc_profit`              decimal(20,6)        DEFAULT NULL  COMMENT    '奖金包_BBC定价毛利率',
`salary_sales_value`             decimal(20,6)        DEFAULT NULL  COMMENT    '奖金包_销售额',
`salary_profit`                  decimal(20,6)        DEFAULT NULL  COMMENT    '奖金包_定价毛利额',
`receivable_amount`              decimal(20,6)        DEFAULT NULL  COMMENT    '应收金额',
`overdue_amount`                 decimal(20,6)        DEFAULT NULL  COMMENT    '逾期金额',
`rp_sales_sale_fp_rate`          decimal(20,6)        DEFAULT NULL  COMMENT    '销售员_日配销售额分配比例',
`rp_sales_profit_fp_rate`        decimal(20,6)        DEFAULT NULL  COMMENT    '销售员_日配毛利额分配比例',
`fl_sales_sale_fp_rate`          decimal(20,6)        DEFAULT NULL  COMMENT    '销售员_福利销售额分配比例',
`fl_sales_profit_fp_rate`        decimal(20,6)        DEFAULT NULL  COMMENT    '销售员_福利毛利额分配比例',
`bbc_sales_sale_fp_rate`         decimal(20,6)        DEFAULT NULL  COMMENT    '销售员_BBC销售额分配比例',
`bbc_sales_profit_fp_rate`       decimal(20,6)        DEFAULT NULL  COMMENT    '销售员_BBC毛利额分配比例',
`rp_service_user_sale_fp_rate`   decimal(20,6)        DEFAULT NULL  COMMENT    '服务管家_日配销售额分配比例',
`rp_service_user_profit_fp_rate` decimal(20,6)        DEFAULT NULL  COMMENT    '服务管家_日配毛利额分配比例',
`fl_service_user_sale_fp_rate`   decimal(20,6)        DEFAULT NULL  COMMENT    '服务管家_福利销售额分配比例',
`fl_service_user_profit_fp_rate` decimal(20,6)        DEFAULT NULL  COMMENT    '服务管家_福利毛利额分配比例',
`bbc_service_user_sale_fp_rate`  decimal(20,6)        DEFAULT NULL  COMMENT    '服务管家_BBC销售额分配比例',
`bbc_service_user_profit_fp_rate`decimal(20,6)        DEFAULT NULL  COMMENT    '服务管家_BBC毛利额分配比例',
`sales_over_rate`                decimal(20,6)        DEFAULT NULL  COMMENT    '销售员逾期系数',
`rp_service_user_over_rate`      decimal(20,6)        DEFAULT NULL  COMMENT    '日配服务管家逾期系数',
`fl_service_user_over_rate`      decimal(20,6)        DEFAULT NULL  COMMENT    '福利服务管家逾期系数',
`bbc_service_user_over_rate`     decimal(20,6)        DEFAULT NULL  COMMENT    'BBC服务管家逾期系数',
`rp_service_receivable_amount`   decimal(20,6)        DEFAULT NULL  COMMENT    '日配服务管家应收金额',
`rp_service_overdue_amount`      decimal(20,6)        DEFAULT NULL  COMMENT    '日配服务管家逾期金额',
`fl_service_receivable_amount`   decimal(20,6)        DEFAULT NULL  COMMENT    '福利服务管家应收金额',
`fl_service_overdue_amount`      decimal(20,6)        DEFAULT NULL  COMMENT    '福利服务管家逾期金额',
`bbc_service_receivable_amount`  decimal(20,6)        DEFAULT NULL  COMMENT    'BBC服务管家应收金额',
`bbc_service_overdue_amount`     decimal(20,6)        DEFAULT NULL  COMMENT    'BBC服务管家逾期金额',
`sales_sales_value_ytd`          decimal(20,6)        DEFAULT NULL  COMMENT    '销售员年至今销售额',
`sales_rp_bbc_sales_value_ytd`   decimal(20,6)        DEFAULT NULL  COMMENT    '销售员年至今日配BBC销售额',
`sales_fl_sales_value_ytd`       decimal(20,6)        DEFAULT NULL  COMMENT    '销售员年至今福利销售额',
`tc_rp_sales_value_sales`        decimal(20,6)        DEFAULT NULL  COMMENT    '提成_销售员_日配销售额',
`tc_rp_profit_sales`             decimal(20,6)        DEFAULT NULL  COMMENT    '提成_销售员_日配毛利额',
`tc_fl_sales_value_sales`        decimal(20,6)        DEFAULT NULL  COMMENT    '提成_销售员_福利销售额',
`tc_fl_profit_sales`             decimal(20,6)        DEFAULT NULL  COMMENT    '提成_销售员_福利毛利额',
`tc_bbc_sales_value_sales`       decimal(20,6)        DEFAULT NULL  COMMENT    '提成_销售员_bbc销售额',
`tc_bbc_profit_sales`            decimal(20,6)        DEFAULT NULL  COMMENT    '提成_销售员_bbc毛利额',
`tc_sales`                       decimal(20,6)        DEFAULT NULL  COMMENT    '提成_销售员',
`tc_rp_sales_value_service`      decimal(20,6)        DEFAULT NULL  COMMENT    '提成_日配服务管家_日配销售额',
`tc_rp_profit_service`           decimal(20,6)        DEFAULT NULL  COMMENT    '提成_日配服务管家_日配毛利额',
`tc_rp_service`                  decimal(20,6)        DEFAULT NULL  COMMENT    '提成_日配服务管家',
`tc_fl_sales_value_service`      decimal(20,6)        DEFAULT NULL  COMMENT    '提成_福利服务管家_福利销售额',
`tc_fl_profit_service`           decimal(20,6)        DEFAULT NULL  COMMENT    '提成_福利服务管家_福利毛利额',
`tc_fl_service`                  decimal(20,6)        DEFAULT NULL  COMMENT    '提成_福利服务管家',
`tc_bbc_sales_value_service`     decimal(20,6)        DEFAULT NULL  COMMENT    '提成_BBC服务管家_BBC销售额',
`tc_bbc_profit_service`          decimal(20,6)        DEFAULT NULL  COMMENT    '提成_BBC服务管家_BBC毛利额',
`tc_bbc_service`                 decimal(20,6)        DEFAULT NULL  COMMENT    '提成_BBC服务管家',
`create_by`                      varchar(64)          DEFAULT NULL  COMMENT    '创建人',
`create_time`                    datetime             DEFAULT NULL  COMMENT    '同步时间',
`update_time`                    datetime             DEFAULT NULL  COMMENT    '更新时间',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT     '日期分区',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户提成宽表';


