--hive 客户逾期表
drop table if exists csx_tmp.report_sss_r_m_crm_customer_over_rate_detail;
create table csx_tmp.report_sss_r_m_crm_customer_over_rate_detail(
`biz_id`                             string              COMMENT    '业务主键',
`region_code`                        string              COMMENT    '大区编码',
`region_name`                        string              COMMENT    '大区名称',
`province_code`                      string              COMMENT    '省区编码',
`province_name`                      string              COMMENT    '省区名称',
`city_group_code`                    string              COMMENT    '城市组编码',
`city_group_name`                    string              COMMENT    '城市组名称',
`yearmonth`                          string              COMMENT    '年月',
`channel_code`                       string              COMMENT    '渠道编码',
`channel_name`                       string              COMMENT    '渠道名称',
`customer_id`                        string              COMMENT    '客户ID',
`customer_no`                        string              COMMENT    '客户编号',
`customer_name`                      string              COMMENT    '客户名称',
`sales_id`                           string              COMMENT    '销售员ID',
`work_no`                            string              COMMENT    '销售员工号',
`sales_name`                         string              COMMENT    '销售员名称',
`rp_service_user_id`                 string              COMMENT    '日配服务管家ID',
`rp_service_user_work_no`            string              COMMENT    '日配服务管家工号',
`rp_service_user_name`               string              COMMENT    '日配服务管家名称',
`fl_service_user_id`                 string              COMMENT    '福利服务管家ID',
`fl_service_user_work_no`            string              COMMENT    '福利服务管家工号',
`fl_service_user_name`               string              COMMENT    '福利服务管家名称',
`bbc_service_user_id`                string              COMMENT    'bbc服务管家ID',
`bbc_service_user_work_no`           string              COMMENT    'bbc服务管家工号',
`bbc_service_user_name`              string              COMMENT    'bbc服务管家名称',
`payment_terms`                      string              COMMENT    '账期类型',
`payment_days`                       int                 COMMENT    '账期天数',
`payment_name`                       string              COMMENT    '账期名称',
`company_code`                       string              COMMENT    '公司编码',
`company_name`                       string              COMMENT    '公司名称',
`receivable_amount`                  decimal(20,6)       COMMENT    '应收金额',
`overdue_amount`                     decimal(20,6)       COMMENT    '逾期金额',
`overdue_coefficient_numerator`      decimal(20,6)       COMMENT    '逾期金额*逾期天数',
`overdue_coefficient_denominator`    decimal(20,6)       COMMENT    '应收金额*帐期天数',
`over_rate`                          decimal(20,6)       COMMENT    '逾期系数',
`is_greater_0`                       string              COMMENT    '应收大于0',
`create_by`                          string              COMMENT    '创建人',
`create_time`                        timestamp           COMMENT    '创建时间',
`update_time`                        timestamp           COMMENT    '更新时间'

) COMMENT '客户逾期表'
PARTITIONED BY (sdt string COMMENT '分区')
STORED AS TEXTFILE;


--mysql 客户逾期表
CREATE TABLE `report_sss_r_m_crm_customer_over_rate_detail` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(50)          NOT NULL  COMMENT    '业务主键',
`region_code`                    varchar(16)          not NULL COMMENT    '大区编码',
`region_name`                    varchar(16)          not NULL COMMENT    '大区名称',
`province_code`                  varchar(16)          not NULL COMMENT    '省区编码',
`province_name`                  varchar(16)          not NULL COMMENT    '省区名称',
`city_group_code`                varchar(16)          not NULL COMMENT    '城市组编码',
`city_group_name`                varchar(16)          not NULL COMMENT    '城市组名称',
`yearmonth`                      varchar(16)          not NULL COMMENT    '年月',
`channel_code`                   varchar(16)          not NULL COMMENT    '渠道编码',
`channel_name`                   varchar(16)          not NULL COMMENT    '渠道名称',
`customer_id`                    varchar(16)          not NULL COMMENT    '客户ID',
`customer_no`                    varchar(16)          not NULL COMMENT    '客户编号',
`customer_name`                  varchar(64)          not NULL COMMENT    '客户名称',
`sales_id`                       varchar(16)          not NULL COMMENT    '销售员ID',
`work_no`                        varchar(16)          not NULL COMMENT    '销售员工号',
`sales_name`                     varchar(16)          not NULL COMMENT    '销售员名称',
`rp_service_user_id`             varchar(16)          DEFAULT NULL COMMENT    '日配服务管家ID',
`rp_service_user_work_no`        varchar(16)          DEFAULT NULL COMMENT    '日配服务管家工号',
`rp_service_user_name`           varchar(16)          DEFAULT NULL COMMENT    '日配服务管家名称',
`fl_service_user_id`             varchar(16)          DEFAULT NULL COMMENT    '福利服务管家ID',
`fl_service_user_work_no`        varchar(16)          DEFAULT NULL COMMENT    '福利服务管家工号',
`fl_service_user_name`           varchar(16)          DEFAULT NULL COMMENT    '福利服务管家名称',
`bbc_service_user_id`            varchar(16)          DEFAULT NULL COMMENT    'bbc服务管家ID',
`bbc_service_user_work_no`       varchar(16)          DEFAULT NULL COMMENT    'bbc服务管家工号',
`bbc_service_user_name`          varchar(16)          DEFAULT NULL COMMENT    'bbc服务管家名称',
`payment_terms`                  varchar(16)          DEFAULT NULL COMMENT    '账期类型',
`payment_days`                   int                  DEFAULT NULL COMMENT    '账期天数',
`payment_name`                   varchar(16)          DEFAULT NULL COMMENT    '账期名称',
`company_code`                   varchar(16)          DEFAULT NULL COMMENT    '公司编码',
`company_name`                   varchar(16)          DEFAULT NULL COMMENT    '公司名称',
`receivable_amount`              decimal(20,6)        DEFAULT NULL COMMENT    '应收金额',
`overdue_amount`                 decimal(20,6)        DEFAULT NULL COMMENT    '逾期金额',
`overdue_coefficient_numerator`  decimal(20,6)        DEFAULT NULL COMMENT    '逾期金额*逾期天数',
`overdue_coefficient_denominator`decimal(20,6)        DEFAULT NULL COMMENT    '应收金额*帐期天数',
`over_rate`                      decimal(20,6)        DEFAULT NULL COMMENT    '逾期系数',
`is_greater_0`                   varchar(16)          DEFAULT NULL COMMENT    '应收大于0',
`create_by`                      varchar(64)          DEFAULT NULL COMMENT    '创建人',
`create_time`                    datetime             DEFAULT NULL COMMENT    '创建时间',
`update_time`                    datetime             DEFAULT NULL COMMENT    '更新时间',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT    '统计日期',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户逾期表';