
insert overwrite table csx_analyse.csx_analyse_fr_oms_complaint_detail_new_di

select
	id,complaint_code,complaint_time,complaint_status_code,performance_region_code,performance_region_name,performance_province_code,performance_province_name,
	performance_city_code,performance_city_name,sale_order_code,a.customer_code,customer_name,sub_customer_code,sub_customer_name,sales_user_id,sales_user_number,
	sales_user_name,first_category_code,first_category_name,second_category_code,second_category_name,third_category_code,third_category_name,sign_company_code,
	sign_company_name,inventory_dc_code,inventory_dc_name,inventory_dc_province_code,inventory_dc_province_name,inventory_dc_city_code,inventory_dc_city_name,
	require_delivery_date,complaint_dimension,complaint_type_code,complaint_type_name,main_category_code,main_category_name,sub_category_code,sub_category_name,
	goods_code,goods_name,classify_large_code,classify_large_name,classify_middle_code,classify_middle_name,classify_small_code,classify_small_name,complaint_qty,
	unit_name,purchase_qty,purchase_unit_name,purchase_unit_rate,sale_price,complaint_amt,complaint_describe,
	regexp_replace(evidence_imgs,'\\[\\"|\\"\\]|\\[|\\]','') as evidence_imgs,
	channel_type_code,responsible_user_id,
	responsible_user_name,designee_user_id,designee_user_name,first_level_department_code,first_level_department_name,second_level_department_code,second_level_department_name,
	department_responsible_user_id,department_responsible_user_name,replenishment_order_code,create_by_id,create_by,create_time,update_by,update_time,complaint_deal_time,
	reason,
	regexp_replace(result,'\n|\t|\r|\,|\"|\\\\n','') as result,
	-- result,
	plan,complaint_deal_status,disagree_reason,replay_report,reject_reason,disagreement_reason,complaint_reject_status,task_sync_time,complaint_date,
	basic_performance_province_code,basic_performance_province_name,basic_performance_city_code,basic_performance_city_name,
	feedback_user_id,feedback_user_name,feedback_time,refund_code,cancel_reason,need_process,generate_reason,process_result,deal_detail_id,complaint_node_code,
	complaint_node_name,recep_order_user_number,recep_order_by,
	complaint_date_time,complaint_time_de,deal_date,
	processing_time,complaint_status_name,complaint_deal_status_name,
	b.user_number as create_by_user_number,
	coalesce(a.detail_plan,'') as detail_plan,a.complaint_level,a.complaint_level_name,a.department_name,
	sdt,
	case when c.customer_code is not null then '是' else '否' end as strategy_status_name,
	coalesce(c.strategy_user_number,'') as strategy_user_number,
	coalesce(c.strategy_user_name,'') as strategy_user_name,
	case when a.diff_days_1<=6 or a.diff_days_2<=6 then '是' else '否' end as is_repeat
from 
	(
	select 
		*,
		concat(substr(create_time,1,4),'年',substr(create_time,6,2),'月',substr(create_time,9,2),'日') as complaint_date_time,
		substr(create_time,12,8) as complaint_time_de,
		regexp_replace(substr(complaint_deal_time,1,10),'-','') as deal_date,
		round((unix_timestamp(complaint_deal_time)-unix_timestamp(create_time))/3600,2) as processing_time,
		case when complaint_status_code=10 then '待判责'
			when complaint_status_code=20 then '处理中'
			when complaint_status_code=21 then '待审核'
			when complaint_status_code=30 then '已完成'
			when complaint_status_code=-1 then '已取消'
		end as complaint_status_name,
		case when complaint_deal_status=10 then '待处理'
			when complaint_deal_status=20 then '待修改'
			when complaint_deal_status=30 then '已处理待审'
			when complaint_deal_status=31 then '已驳回待审核'
			when complaint_deal_status=40 then '已完成'
			when complaint_deal_status=-1 then '已取消'
		end as complaint_deal_status_name,
		case when complaint_level=0 then '一级紧急'
			when complaint_level=1 then '一级非紧急'
			when complaint_level=2 then '二级'
			when complaint_level=3 then '三级'
			when complaint_level=-1 or complaint_level is null or complaint_level='' then '无等级'
			else '其他'
		end as complaint_level_name,
		coalesce(concat(first_level_department_name,'-',second_level_department_name),'') as department_name,
		row_number()over(partition by performance_city_code,classify_small_code,sub_category_code,first_level_department_code order by create_time) as rn,
		datediff(to_date(create_time),to_date(lead(create_time,1,null)over(partition by performance_city_code,classify_small_code,sub_category_code,first_level_department_code,complaint_node_code order by create_time desc))) as diff_days_1,
		datediff(to_date(lag(create_time,1,null)over(partition by performance_city_code,classify_small_code,sub_category_code,first_level_department_code,complaint_node_code order by create_time desc)),to_date(create_time)) as diff_days_2
	from 
		csx_dws.csx_dws_oms_complaint_detail_di
	) a 
	left join
		(
		select 
			user_id,user_number,user_name 
		from 
			csx_dim.csx_dim_uc_user
		where 
			sdt='current' 
			and delete_flag = '0'
		group by 
			user_id,user_number,user_name 
		) b on b.user_id=a.create_by_id
	left join
		(
		select	
			customer_code,strategy_status,strategy_user_id,strategy_user_number,strategy_user_name
		from 
			csx_dim.csx_dim_crm_customer_info
		where 
			sdt = 'current' and strategy_status = 1 -- 是否为战略客户 0否 1是
		) c on c.customer_code=a.customer_code
;
	
/*
--------------------------------- hive建表语句 -------------------------------
-- csx_analyse.csx_analyse_fr_oms_complaint_detail_new_di  客诉明细表

drop table if exists csx_analyse.csx_analyse_fr_oms_complaint_detail_new_di;
create table csx_analyse.csx_analyse_fr_oms_complaint_detail_new_di(
`id`                             bigint              COMMENT    'id',
`complaint_code`                 string              COMMENT    '客诉单编码',
`complaint_time`                 timestamp           COMMENT    '客诉发生时间',
`complaint_status_code`          int                 COMMENT    '客诉状态: 10-待处理 20-已处理待确认 21-驳回待确认  30-已处理 -1-已取消',
`performance_region_code`        string              COMMENT    '业绩大区编码',
`performance_region_name`        string              COMMENT    '业绩大区名称',
`performance_province_code`      string              COMMENT    '业绩省区编码',
`performance_province_name`      string              COMMENT    '业绩省区名称',
`performance_city_code`          string              COMMENT    '业绩城市编码',
`performance_city_name`          string              COMMENT    '业绩城市名称',
`sale_order_code`                string              COMMENT    '销售订单编码',
`customer_code`                  string              COMMENT    '客户编码',
`customer_name`                  string              COMMENT    '客户名称',
`sub_customer_code`              string              COMMENT    '子客户编码',
`sub_customer_name`              string              COMMENT    '子客户名称',
`sales_user_id`                  bigint              COMMENT    '业务员id',
`sales_user_number`              string              COMMENT    '业务员工号',
`sales_user_name`                string              COMMENT    '业务员名称',
`first_category_code`            string              COMMENT    '一级客户分类编码',
`first_category_name`            string              COMMENT    '一级客户分类名称',
`second_category_code`           string              COMMENT    '二级客户分类编码',
`second_category_name`           string              COMMENT    '二级客户分类名称',
`third_category_code`            string              COMMENT    '三级客户分类编码',
`third_category_name`            string              COMMENT    '三级客户分类名称',
`sign_company_code`              string              COMMENT    '签约公司编码',
`sign_company_name`              string              COMMENT    '签约公司名称',
`inventory_dc_code`              string              COMMENT    '库存地点编码',
`inventory_dc_name`              string              COMMENT    '库存地点名称',
`inventory_dc_province_code`     string              COMMENT    '库存地点省区编码',
`inventory_dc_province_name`     string              COMMENT    '库存地点省区名称',
`inventory_dc_city_code`         string              COMMENT    '库存地点城市编码',
`inventory_dc_city_name`         string              COMMENT    '库存地点城市名称',
`require_delivery_date`          int                 COMMENT    '要求送货日期',
`complaint_dimension`            int                 COMMENT    '客诉维度 1-订单 2-商品',
`complaint_type_code`            string              COMMENT    '客诉类型编码(小类)',
`complaint_type_name`            string              COMMENT    '客诉类型',
`main_category_code`             string              COMMENT    '客诉大类编码',
`main_category_name`             string              COMMENT    '客诉大类名称',
`sub_category_code`              string              COMMENT    '客诉小类编码',
`sub_category_name`              string              COMMENT    '客诉小类名称',
`goods_code`                     string              COMMENT    '商品编码',
`goods_name`                     string              COMMENT    '商品名称',
`classify_large_code`            string              COMMENT    '管理大类编号',
`classify_large_name`            string              COMMENT    '管理大类名称',
`classify_middle_code`           string              COMMENT    '管理中类编号',
`classify_middle_name`           string              COMMENT    '管理中类名称',
`classify_small_code`            string              COMMENT    '管理小类编号',
`classify_small_name`            string              COMMENT    '管理小类名称',
`complaint_qty`                  decimal(11,3)       COMMENT    '基础单位客诉商品数量',
`unit_name`                      string              COMMENT    '基础单位',
`purchase_qty`                   decimal(11,3)       COMMENT    '下单数量',
`purchase_unit_name`             string              COMMENT    '下单单位',
`purchase_unit_rate`             decimal(13,2)       COMMENT    '下单单位转换比例',
`sale_price`                     decimal(15,2)       COMMENT    '商品单价',
`complaint_amt`                  decimal(15,2)       COMMENT    '客诉金额',
`complaint_describe`             string              COMMENT    '问题描述',
`evidence_imgs`                  string              COMMENT    '凭证地址',
`channel_type_code`              int                 COMMENT    '渠道 1-oms 2-crm',
`responsible_user_id`            bigint              COMMENT    '客诉责任人id',
`responsible_user_name`          string              COMMENT    '客诉负责人姓名',
`designee_user_id`               bigint              COMMENT    '被指派人id',
`designee_user_name`             string              COMMENT    '被指派人姓名',
`first_level_department_code`    string              COMMENT    '一级部门编码',
`first_level_department_name`    string              COMMENT    '一级部门名称',
`second_level_department_code`   string              COMMENT    '二级部门编码',
`second_level_department_name`   string              COMMENT    '二级部门名称',
`department_responsible_user_id` bigint              COMMENT    '部门责任人id',
`department_responsible_user_name` string              COMMENT    '部门责任人姓名',
`replenishment_order_code`       string              COMMENT    '补货单号',
`create_by_id`                   bigint              COMMENT    '创建人id',
`create_by`                      string              COMMENT    '创建人',
`create_time`                    timestamp           COMMENT    '创建时间',
`update_by`                      string              COMMENT    '更新人',
`update_time`                    timestamp           COMMENT    '更新时间',
`complaint_deal_time`            timestamp           COMMENT    '客诉处理时间',
`reason`                         string              COMMENT    '产生原因',
`result`                         string              COMMENT    '处理结果',
`plan`                           string              COMMENT    '改进方案',
`complaint_deal_status`          int                 COMMENT    '责任环节状态编码',
`disagree_reason`                string              COMMENT    '不认同理由',
`replay_report`                  string              COMMENT    '复盘报告',
`reject_reason`                  string              COMMENT    '驳回理由',
`disagreement_reason`            string              COMMENT    '不同意驳回理由',
`complaint_reject_status`        string              COMMENT    '状态 1-新的驳回 2-处理完成',
`task_sync_time`                 timestamp           COMMENT    '任务同步时间',
`complaint_date`                 string              COMMENT    '客诉发生日期',
`basic_performance_province_code`string              COMMENT    '主数据业绩归属省区',
`basic_performance_province_name`string              COMMENT    '主数据业绩归属省区名称',
`basic_performance_city_code`    string              COMMENT    '主数据业绩归属城市',
`basic_performance_city_name`    string              COMMENT    '主数据业绩归属城市名称',
`feedback_user_id`               bigint              COMMENT    '处理人id',
`feedback_user_name`             string              COMMENT    '处理人',
`feedback_time`                  string              COMMENT    '反馈时间',
`refund_code`                    string              COMMENT    '退货单号',
`cancel_reason`                  string              COMMENT    '取消原因',
`need_process`                   int                 COMMENT    '是否判责(-1.待判责 0-无需判责 1-已判责)',
`generate_reason`                string              COMMENT    '产生原因',
`process_result`                 string              COMMENT    '处理结果',
`deal_detail_id`                 bigint              COMMENT    '客诉处理id',
`complaint_node_code`            string              COMMENT    '客诉环节编码',
`complaint_node_name`            string              COMMENT    '客诉环节名称',
`recep_order_user_number`        string              COMMENT    '接单人工号',
`recep_order_by`                 string              COMMENT    '接单人名称',
`complaint_date_time`            string              COMMENT    '客诉日期',
`complaint_time_de`              string              COMMENT    '客诉时间',
`deal_date`                      string              COMMENT    '处理日期',
`processing_time`                decimal(15,6)       COMMENT    '处理时长',
`complaint_status_name`          string              COMMENT    '客诉单状态',
`complaint_deal_status_name`     string              COMMENT    '责任环节状态',
`create_by_user_number`          string              COMMENT    '创建人工号',
`detail_plan`                    string              COMMENT    '详细举措',
`complaint_level`                int                 COMMENT    '客诉等级：0-一级紧急 1-一级非紧急 2-二级 3-三级',
`complaint_level_name`           string              COMMENT    '客诉等级描述',
`department_name`                string              COMMENT    '责任部门合并',
sdt string COMMENT '客诉日期分区'

) COMMENT '客诉明细表'
STORED AS PARQUET;

*/


CREATE TABLE `dws_oms_r_d_complaint_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `biz_id` varchar(32) NOT NULL COMMENT '表业务主键(客诉单号+责任部门+处理环节)',
  `complaint_no` varchar(40) NOT NULL COMMENT '客诉单号',
  `complaint_time` varchar(30) NOT NULL COMMENT '客诉发生时间',
  `order_no` varchar(40) NOT NULL COMMENT '订单编号',
  `region_code` varchar(4) NOT NULL COMMENT '大区编码',
  `region_name` varchar(20) NOT NULL COMMENT '大区名称',
  `province_code` varchar(8) NOT NULL COMMENT '省区编码',
  `province_name` varchar(20) NOT NULL COMMENT '省区名称',
  `city_group_code` varchar(10) NOT NULL COMMENT '城市组编码',
  `city_group_name` varchar(20) NOT NULL COMMENT '城市组名称',
  `customer_no` varchar(20) NOT NULL COMMENT '客户编码',
  `customer_name` varchar(128) NOT NULL COMMENT '客户名称',
  `sub_customer_code` varchar(20) NOT NULL COMMENT '子客户编码',
  `sub_customer_name` varchar(200) NOT NULL COMMENT '子客户名称',
  `sales_id` bigint(20) NOT NULL COMMENT '业务员Id',
  `work_no` varchar(20) NOT NULL COMMENT '业务员工号',
  `sales_name` varchar(32) NOT NULL COMMENT '业务员名称',
  `first_category_code` varchar(8) NOT NULL COMMENT '一级客户分类编码',
  `first_category_name` varchar(30) NOT NULL COMMENT '一级客户分类名称',
  `second_category_code` varchar(8) NOT NULL COMMENT '二级客户分类编码',
  `second_category_name` varchar(50) NOT NULL COMMENT '二级客户分类名称',
  `third_category_code` varchar(8) NOT NULL COMMENT '三级客户分类编码',
  `third_category_name` varchar(50) NOT NULL COMMENT '三级客户分类名称',
  `sign_company_code` varchar(8) NOT NULL COMMENT '签约公司编码',
  `sign_company_name` varchar(100) NOT NULL COMMENT '签约公司名称',
  `inventory_dc_code` varchar(8) NOT NULL COMMENT '库存地点编码',
  `inventory_dc_name` varchar(100) NOT NULL COMMENT '库存地点名称',
  `inventory_dc_province_code` varchar(20) NOT NULL COMMENT '库存地点所属省区编码',
  `inventory_dc_province_name` varchar(20) NOT NULL COMMENT '库存地点所属省区名称',
  `inventory_dc_city_code` varchar(20) NOT NULL COMMENT '库存地点所属城市编码',
  `inventory_dc_city_name` varchar(20) NOT NULL COMMENT '库存地点所属城市名称',
  `require_delivery_date` int(11) NOT NULL COMMENT '要求送货日期',
  `complaint_dimension` int(11) NOT NULL COMMENT '客诉维度 1-订单 2-商品',
  `complaint_type_code` varchar(10) NOT NULL COMMENT '客诉类型编码(小类)',
  `complaint_type_name` varchar(60) NOT NULL COMMENT '客诉类型',
  `main_category_code` varchar(10) NOT NULL COMMENT '客诉大类编码',
  `main_category_name` varchar(30) NOT NULL COMMENT '客诉大类名称',
  `sub_category_code` varchar(10) NOT NULL COMMENT '客诉小类编码',
  `sub_category_name` varchar(60) NOT NULL COMMENT '客诉小类名称',
  `goods_code` varchar(18) NOT NULL COMMENT '商品编码',
  `goods_name` varchar(128) NOT NULL COMMENT '商品名称',
  `classify_large_code` varchar(8) NOT NULL COMMENT '管理大类编号',
  `classify_large_name` varchar(20) NOT NULL COMMENT '管理大类名称',
  `classify_middle_code` varchar(8) NOT NULL COMMENT '管理中类编号',
  `classify_middle_name` varchar(20) NOT NULL COMMENT '管理中类名称',
  `classify_small_code` varchar(8) NOT NULL COMMENT '管理小类编号',
  `classify_small_name` varchar(40) NOT NULL COMMENT '管理小类名称',
  `qty` decimal(11,3) NOT NULL COMMENT '基础单位客诉商品数量',
  `unit` varchar(40) NOT NULL COMMENT '基础单位',
  `purchase_qty` decimal(11,3) NOT NULL COMMENT '下单数量',
  `purchase_unit` varchar(40) NOT NULL COMMENT '下单单位',
  `purchase_unit_rate` decimal(13,2) NOT NULL COMMENT '下单单位转换比例',
  `sale_price` decimal(15,2) NOT NULL COMMENT '商品单价',
  `complaint_price` decimal(15,2) NOT NULL COMMENT '客诉金额',
  `complaint_describe` varchar(500) NOT NULL COMMENT '问题描述',
  `evidence_imgs` varchar(1000) NOT NULL COMMENT '凭证',
  `channel_type` int(11) NOT NULL COMMENT '渠道 1-OMS 2-CRM',
  `responsible_person_id` bigint(20) DEFAULT NULL COMMENT '客诉责任人id',
  `responsible_person_name` varchar(30) DEFAULT NULL COMMENT '客诉负责人姓名',
  `designee_id` bigint(20) NOT NULL COMMENT '被指派人id',
  `designee_name` varchar(30) NOT NULL COMMENT '被指派人姓名',
  `first_level_department_code` varchar(40) DEFAULT NULL COMMENT '一级责任部门编码',
  `first_level_department_name` varchar(40) DEFAULT NULL COMMENT '一级责任部门名称',
  `responsible_department_code` varchar(40) DEFAULT NULL COMMENT '二级责任部门编码',
  `responsible_department_name` varchar(40) DEFAULT NULL COMMENT '二级责任部门名称',
  `department_responsible_person_id` bigint(20) DEFAULT NULL COMMENT '部门责任人id',
  `department_responsible_person_name` varchar(80) DEFAULT NULL COMMENT '部门责任人姓名',
  `complaint_status` int(11) NOT NULL COMMENT '客诉状态: 10-待处理 20-已处理待确认 21-驳回待确认  30-已处理 -1-已取消',
  `create_by_id` bigint(20) NOT NULL COMMENT '创建人id',
  `create_by` varchar(20) NOT NULL COMMENT '创建人',
  `create_time` varchar(30) NOT NULL COMMENT '创建时间',
  `update_by` varchar(20) NOT NULL COMMENT '更新人',
  `update_time` varchar(30) NOT NULL COMMENT '更新时间',
  `complaint_deal_time` varchar(30) DEFAULT NULL COMMENT '客诉处理时间',
  `reason` varchar(1000) DEFAULT NULL COMMENT '产生原因',
  `result` varchar(1000) DEFAULT NULL COMMENT '处理结果',
  `plan` varchar(1000) DEFAULT NULL COMMENT '改进方案',
  `complaint_deal_status` int(11) DEFAULT NULL COMMENT '(废弃)是否认同 1-认同 2-不认同',
  `disagree_reason` varchar(200) DEFAULT NULL COMMENT '(废弃)不认同理由',
  `replay_report` varchar(500) DEFAULT NULL COMMENT '复盘报告',
  `reject_reason` varchar(400) DEFAULT NULL COMMENT '驳回理由',
  `disagreement_reason` varchar(200) DEFAULT NULL COMMENT '不同意驳回理由',
  `complaint_reject_status` varchar(50) DEFAULT NULL COMMENT '状态 1-新的驳回 2-处理完成',
  `sdt` varchar(16) NOT NULL COMMENT '客诉创建日期',
  `basic_performance_province_code` varchar(32) NOT NULL COMMENT '主数据业绩归属省区编码',
  `basic_performance_province_name` varchar(32) NOT NULL COMMENT '主数据业绩归属省区名称',
  `basic_performance_city_code` varchar(32) NOT NULL COMMENT '主数据业绩归属城市编码',
  `basic_performance_city_name` varchar(32) NOT NULL COMMENT '主数据业绩归属城市名称',
  `complaint_node_code` varchar(10) DEFAULT NULL COMMENT '客诉环节编码',
  `complaint_node_name` varchar(10) DEFAULT NULL COMMENT '客诉环节名称',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_complaint_biz_id` (`biz_id`),
  KEY `idx_complaint_status` (`complaint_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=60660001 COMMENT='客诉单';



CREATE TABLE `csx_analyse_fr_oms_complaint_detail_new_di` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
`biz_id`                             bigint              NOT NULL COMMENT    '业务主键',
`complaint_code`                 varchar(64)         NOT NULL COMMENT    '客诉单编码',
`complaint_time`                 datetime            NOT NULL COMMENT    '客诉发生时间',
`complaint_status_code`          int                 NOT NULL COMMENT    '客诉状态: 10-待处理 20-已处理待确认 21-驳回待确认  30-已处理 -1-已取消',
`performance_region_code`        varchar(16)         NOT NULL DEFAULT '' COMMENT    '业绩大区编码',
`performance_region_name`        varchar(64)         NOT NULL DEFAULT '' COMMENT    '业绩大区名称',
`performance_province_code`      varchar(16)         NOT NULL DEFAULT '' COMMENT    '业绩省区编码',
`performance_province_name`      varchar(64)         NOT NULL DEFAULT '' COMMENT    '业绩省区名称',
`performance_city_code`          varchar(16)         NOT NULL DEFAULT '' COMMENT    '业绩城市编码',
`performance_city_name`          varchar(64)         NOT NULL DEFAULT '' COMMENT    '业绩城市名称',
`sale_order_code`                varchar(16)         NOT NULL DEFAULT '' COMMENT    '销售订单编码',
`customer_code`                  varchar(16)         NOT NULL DEFAULT '' COMMENT    '客户编码',
`customer_name`                  varchar(64)         NOT NULL DEFAULT '' COMMENT    '客户名称',
`sub_customer_code`              varchar(16)         NOT NULL DEFAULT '' COMMENT    '子客户编码',
`sub_customer_name`              varchar(64)         NOT NULL DEFAULT '' COMMENT    '子客户名称',
`sales_user_id`                  bigint              NOT NULL DEFAULT 0 COMMENT    '业务员id',
`sales_user_number`              varchar(16)         NOT NULL DEFAULT '' COMMENT    '业务员工号',
`sales_user_name`                varchar(64)         NOT NULL DEFAULT '' COMMENT    '业务员名称',
`first_category_code`            varchar(16)         NOT NULL DEFAULT '' COMMENT    '一级客户分类编码',
`first_category_name`            varchar(64)         NOT NULL DEFAULT '' COMMENT    '一级客户分类名称',
`second_category_code`           varchar(16)         NOT NULL DEFAULT '' COMMENT    '二级客户分类编码',
`second_category_name`           varchar(64)         NOT NULL DEFAULT '' COMMENT    '二级客户分类名称',
`third_category_code`            varchar(16)         NOT NULL DEFAULT '' COMMENT    '三级客户分类编码',
`third_category_name`            varchar(64)         NOT NULL DEFAULT '' COMMENT    '三级客户分类名称',
`sign_company_code`              varchar(16)         NOT NULL DEFAULT '' COMMENT    '签约公司编码',
`sign_company_name`              varchar(64)         NOT NULL DEFAULT '' COMMENT    '签约公司名称',
`inventory_dc_code`              varchar(16)         NOT NULL DEFAULT '' COMMENT    '库存地点编码',
`inventory_dc_name`              varchar(64)         NOT NULL DEFAULT '' COMMENT    '库存地点名称',
`inventory_dc_province_code`     varchar(16)         NOT NULL DEFAULT '' COMMENT    '库存地点省区编码',
`inventory_dc_province_name`     varchar(64)         NOT NULL DEFAULT '' COMMENT    '库存地点省区名称',
`inventory_dc_city_code`         varchar(16)         NOT NULL DEFAULT '' COMMENT    '库存地点城市编码',
`inventory_dc_city_name`         varchar(64)         NOT NULL DEFAULT '' COMMENT    '库存地点城市名称',
`require_delivery_date`          int                 DEFAULT NULL COMMENT    '要求送货日期',
`complaint_dimension`            int                 DEFAULT NULL COMMENT    '客诉维度 1-订单 2-商品',
`complaint_type_code`            varchar(16)         DEFAULT NULL COMMENT    '客诉类型编码(小类)',
`complaint_type_name`            varchar(64)         DEFAULT NULL COMMENT    '客诉类型',
`main_category_code`             varchar(16)         DEFAULT NULL COMMENT    '客诉大类编码',
`main_category_name`             varchar(64)         DEFAULT NULL COMMENT    '客诉大类名称',
`sub_category_code`              varchar(16)         DEFAULT NULL COMMENT    '客诉小类编码',
`sub_category_name`              varchar(64)         DEFAULT NULL COMMENT    '客诉小类名称',
`goods_code`                     varchar(16)         DEFAULT NULL COMMENT    '商品编码',
`goods_name`                     varchar(64)         DEFAULT NULL COMMENT    '商品名称',
`classify_large_code`            varchar(16)         DEFAULT NULL COMMENT    '管理大类编号',
`classify_large_name`            varchar(64)         DEFAULT NULL COMMENT    '管理大类名称',
`classify_middle_code`           varchar(16)         DEFAULT NULL COMMENT    '管理中类编号',
`classify_middle_name`           varchar(64)         DEFAULT NULL COMMENT    '管理中类名称',
`classify_small_code`            varchar(16)         DEFAULT NULL COMMENT    '管理小类编号',
`classify_small_name`            varchar(64)         DEFAULT NULL COMMENT    '管理小类名称',
`complaint_qty`                  decimal(11,3)       DEFAULT NULL COMMENT    '基础单位客诉商品数量',
`unit_name`                      varchar(16)         DEFAULT NULL COMMENT    '基础单位',
`purchase_qty`                   decimal(11,3)       DEFAULT NULL COMMENT    '下单数量',
`purchase_unit_name`             varchar(16)         DEFAULT NULL COMMENT    '下单单位',
`purchase_unit_rate`             decimal(13,2)       DEFAULT NULL COMMENT    '下单单位转换比例',
`sale_price`                     decimal(15,2)       DEFAULT NULL COMMENT    '商品单价',
`complaint_amt`                  decimal(15,2)       DEFAULT NULL COMMENT    '客诉金额',
`complaint_describe`             varchar(500)        DEFAULT NULL COMMENT    '问题描述',
`evidence_imgs`                  varchar(200)        DEFAULT NULL COMMENT    '凭证地址',
`channel_type_code`              int                 DEFAULT NULL COMMENT    '渠道 1-oms 2-crm',
`responsible_user_id`            bigint              DEFAULT NULL COMMENT    '客诉责任人id',
`responsible_user_name`          varchar(16)         DEFAULT NULL COMMENT    '客诉负责人姓名',
`designee_user_id`               bigint              DEFAULT NULL COMMENT    '被指派人id',
`designee_user_name`             varchar(16)         DEFAULT NULL COMMENT    '被指派人姓名',
`first_level_department_code`    varchar(16)         DEFAULT NULL COMMENT    '一级部门编码',
`first_level_department_name`    varchar(64)         DEFAULT NULL COMMENT    '一级部门名称',
`second_level_department_code`   varchar(16)         DEFAULT NULL COMMENT    '二级部门编码',
`second_level_department_name`   varchar(64)         DEFAULT NULL COMMENT    '二级部门名称',
`department_responsible_user_id` bigint              DEFAULT NULL COMMENT    '部门责任人id',
`department_responsible_user_name`   varchar(16)         DEFAULT NULL COMMENT    '部门责任人姓名',
`replenishment_order_code`       varchar(64)         DEFAULT NULL COMMENT    '补货单号',
`create_by_id`                   bigint              DEFAULT NULL COMMENT    '创建人id',
`create_by`                      varchar(16)         DEFAULT NULL COMMENT    '创建人',
`create_time`                    datetime            DEFAULT NULL COMMENT    '创建时间',
`update_by`                      varchar(64)         DEFAULT NULL COMMENT    '更新人',
`update_time`                    datetime            DEFAULT NULL COMMENT    '更新时间',
`complaint_deal_time`            datetime            DEFAULT NULL COMMENT    '客诉处理时间',
`reason`                         varchar(1000)       DEFAULT NULL COMMENT    '产生原因',
`result`                         varchar(1000)       DEFAULT NULL COMMENT    '处理结果',
`plan`                           varchar(1000)       DEFAULT NULL COMMENT    '改进方案',
`complaint_deal_status`          int                 DEFAULT NULL COMMENT    '责任环节状态编码',
`disagree_reason`                varchar(200)        DEFAULT NULL COMMENT    '不认同理由',
`replay_report`                  varchar(500)        DEFAULT NULL COMMENT    '复盘报告',
`reject_reason`                  varchar(400)        DEFAULT NULL COMMENT    '驳回理由',
`disagreement_reason`            varchar(200)        DEFAULT NULL COMMENT    '不同意驳回理由',
`complaint_reject_status`        varchar(50)         DEFAULT NULL COMMENT    '状态 1-新的驳回 2-处理完成',
`task_sync_time`                 datetime            DEFAULT NULL COMMENT    '任务同步时间',
`complaint_date`                 varchar(16)         DEFAULT NULL COMMENT    '客诉发生日期',
`basic_performance_province_code`varchar(32)         DEFAULT NULL COMMENT    '主数据业绩归属省区',
`basic_performance_province_name`varchar(32)         DEFAULT NULL COMMENT    '主数据业绩归属省区名称',
`basic_performance_city_code`    varchar(32)         DEFAULT NULL COMMENT    '主数据业绩归属城市',
`basic_performance_city_name`    varchar(32)         DEFAULT NULL COMMENT    '主数据业绩归属城市名称',
`feedback_user_id`               bigint              DEFAULT NULL COMMENT    '处理人id',
`feedback_user_name`             varchar(64)         DEFAULT NULL COMMENT    '处理人',
`feedback_time`                  varchar(16)         DEFAULT NULL COMMENT    '反馈时间',
`refund_code`                    varchar(32)         DEFAULT NULL COMMENT    '退货单号',
`cancel_reason`                  varchar(200)        DEFAULT NULL COMMENT    '取消原因',
`need_process`                   int                 DEFAULT NULL COMMENT    '是否判责(-1.待判责 0-无需判责 1-已判责)',
`generate_reason`                varchar(500)        DEFAULT NULL COMMENT    '产生原因',
`process_result`                 varchar(500)        DEFAULT NULL COMMENT    '处理结果',
`deal_detail_id`                 bigint              DEFAULT NULL COMMENT    '客诉处理id',
`complaint_node_code`            varchar(10)         DEFAULT NULL COMMENT    '客诉环节编码',
`complaint_node_name`            varchar(10)         DEFAULT NULL COMMENT    '客诉环节名称',
`recep_order_user_number`        varchar(32)         DEFAULT NULL COMMENT    '接单人工号',
`recep_order_by`                 varchar(32)         DEFAULT NULL COMMENT    '接单人名称',
`complaint_date_time`            varchar(32)         DEFAULT NULL COMMENT    '客诉日期',
`complaint_time_de`              varchar(32)         DEFAULT NULL COMMENT    '客诉时间',
`deal_date`                      varchar(32)         DEFAULT NULL COMMENT    '处理日期',
`processing_time`                decimal(15,6)       DEFAULT NULL COMMENT    '处理时长',
`complaint_status_name`          varchar(32)         DEFAULT NULL COMMENT    '客诉单状态',
`complaint_deal_status_name`     varchar(32)         DEFAULT NULL COMMENT    '责任环节状态',
`create_by_user_number`          varchar(32)         DEFAULT NULL COMMENT    '创建人工号',
`detail_plan`                    varchar(400)        DEFAULT NULL COMMENT    '详细举措',
`complaint_level`                int                 DEFAULT NULL COMMENT    '客诉等级：0-一级紧急 1-一级非紧急 2-二级 3-三级',
`complaint_level_name`           varchar(32)         DEFAULT NULL COMMENT    '客诉等级描述',
`department_name`                varchar(32)         DEFAULT NULL COMMENT    '责任部门合并',
`sdt`                            varchar(16)         DEFAULT NULL COMMENT    '客诉日期分区',
`strategy_status_name`           varchar(16)         DEFAULT NULL COMMENT    '是否战略客户',
`strategy_user_number`           varchar(16)         DEFAULT NULL COMMENT    '战略负责人工号',
`strategy_user_name`             varchar(16)         DEFAULT NULL COMMENT    '战略负责人名称',
`is_repeat`                      varchar(16)         DEFAULT NULL COMMENT    '是否重复客诉',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客诉详情';


truncate table csx_analyse_fr_oms_complaint_detail_new_di

job_hive2mysql_csx_analyse_fr_oms_complaint_detail_new_di
