--hive 大客户提成-订单明细
drop table if exists csx_analyse.csx_analyse_fr_tc_customer_order_detail;
create table csx_analyse.csx_analyse_fr_tc_customer_order_detail(
`biz_id`	string	COMMENT	'业务主键',
`source_bill_no`	string	COMMENT	'来源单号',
`customer_code`	string	COMMENT	'客户编码',
`customer_name`	string	COMMENT	'客户名称',
`credit_code`	string	COMMENT	'信控编号',
`happen_date`	string	COMMENT	'发生日期',
`company_code`	string	COMMENT	'公司代码',
`account_period_code`	string	COMMENT	'账期编码',
`account_period_name`	string	COMMENT	'账期名称',
`account_period_value`	string	COMMENT	'账期值',
`source_sys`	string	COMMENT	'来源系统 mall b端销售 bbc bbc端 begin期初',
`reconciliation_period`	decimal(20,0)	COMMENT	'对账周期',
`bill_date`	string	COMMENT	'结算日期',
`overdue_date`	string	COMMENT	'逾期日期',
`paid_date`	string	COMMENT	'回款核销日期',
`dff`	decimal(20,0)	COMMENT	'回款间隔天数',
`dff_rate`	decimal(20,6)	COMMENT	'回款时间系数',
`order_amt`	decimal(20,6)	COMMENT	'源单据对账金额',
`pay_amt`	decimal(20,6)	COMMENT	'回款核销金额',
`business_type_code`	string	COMMENT	'业务类型编码(1.日配业务 2.福利业务 3.批发内购 4.城市服务商 5.省区大宗 6.bbc 7.大宗一部 8.大宗二部 9.商超)',
`business_type_name`	string	COMMENT	'业务类型名称',
`status`	string	COMMENT	'是否有效',
`sale_amt`	decimal(20,6)	COMMENT	'含税销售额',
`profit`	decimal(20,6)	COMMENT	'含税定价毛利额',
`sale_amt_jiushui`	decimal(20,6)	COMMENT	'销售额_酒水等',
`profit_jiushui`	decimal(20,6)	COMMENT	'毛利额_酒水等',
`region_code`	string	COMMENT	'大区编码',
`region_name`	string	COMMENT	'大区',
`province_code`	string	COMMENT	'省区编码',
`province_name`	string	COMMENT	'省区',
`city_group_code`	string	COMMENT	'城市编码',
`city_group_name`	string	COMMENT	'城市',
`sales_id`	string	COMMENT	'销售员id',
`work_no`	string	COMMENT	'销售员工号',
`sales_name`	string	COMMENT	'销售员',
`rp_service_user_id`	string	COMMENT	'日配客服经理id',
`rp_service_user_work_no`	string	COMMENT	'日配客服经理工号',
`rp_service_user_name`	string	COMMENT	'日配客服经理',
`fl_service_user_id`	string	COMMENT	'福利客服经理id',
`fl_service_user_work_no`	string	COMMENT	'福利客服经理工号',
`fl_service_user_name`	string	COMMENT	'福利客服经理',
`bbc_service_user_id`	string	COMMENT	'bbc客服经理id',
`bbc_service_user_work_no`	string	COMMENT	'bbc客服经理工号',
`bbc_service_user_name`	string	COMMENT	'bbc客服经理',
`rp_sales_fp_rate`	decimal(20,6)	COMMENT	'日配提成系数-销售员',
`fl_sales_sale_fp_rate`	decimal(20,6)	COMMENT	'福利提成系数-销售员',
`bbc_sales_sale_fp_rate`	decimal(20,6)	COMMENT	'BBC提成系数-销售员',
`rp_service_user_fp_rate`	decimal(20,6)	COMMENT	'日配提成系数-日配客服经理',
`fl_service_user_fp_rate`	decimal(20,6)	COMMENT	'福利提成系数-福利客服经理',
`bbc_service_user_fp_rate`	decimal(20,6)	COMMENT	'BBC提成系数-BBC客服经理',
`sales_rp_profit_rate`	decimal(20,6)	COMMENT	'客户日配毛利率-销售员',
`sales_fl_bbc_profit_rate`	decimal(20,6)	COMMENT	'客户福利BBC毛利率-销售员',
`sales_rp_profit_rate_tc`	decimal(20,6)	COMMENT	'客户日配毛利提成比例-销售员',
`sales_fl_bbc_profit_rate_tc`	decimal(20,6)	COMMENT	'客户福利BBC毛利提成比例-销售员',
`rp_service_profit_rate`	decimal(20,6)	COMMENT	'客户日配毛利率-日配客服经理',
`rp_service_profit_rate_tc`	decimal(20,6)	COMMENT	'客户日配毛利提成比例-日配客服经理',
`fl_service_profit_rate`	decimal(20,6)	COMMENT	'客户福利毛利率-福利客服经理',
`fl_service_profit_rate_tc`	decimal(20,6)	COMMENT	'客户福利毛利提成比例-福利客服经理',
`bbc_service_profit_rate`	decimal(20,6)	COMMENT	'客户BBC毛利率-BBC客服经理',
`bbc_service_profit_rate_tc`	decimal(20,6)	COMMENT	'客户BBC毛利提成比例-BBC客服经理',
`sales_profit_basic`	decimal(20,6)	COMMENT	'销售员毛利额_基数',
`sales_profit_finish`	decimal(20,6)	COMMENT	'销售员毛利额_达成',
`sales_target_rate`	decimal(20,6)	COMMENT	'销售员毛利额_达成率',
`sales_target_rate_tc`	decimal(20,6)	COMMENT	'销售员毛利额_达成系数',
`rp_service_profit_basic`	decimal(20,6)	COMMENT	'日配客服经理毛利额_基数',
`rp_service_profit_finish`	decimal(20,6)	COMMENT	'日配客服经理毛利额_达成',
`rp_service_target_rate`	decimal(20,6)	COMMENT	'日配客服经理毛利额_达成率',
`rp_service_target_rate_tc`	decimal(20,6)	COMMENT	'日配客服经理毛利额_达成系数',
`fl_service_profit_basic`	decimal(20,6)	COMMENT	'福利客服经理毛利额_基数',
`fl_service_profit_finish`	decimal(20,6)	COMMENT	'福利客服经理毛利额_达成',
`fl_service_target_rate`	decimal(20,6)	COMMENT	'福利客服经理毛利额_达成率',
`fl_service_target_rate_tc`	decimal(20,6)	COMMENT	'福利客服经理毛利额_达成系数',
`bbc_service_profit_basic`	decimal(20,6)	COMMENT	'BBC客服经理毛利额_基数',
`bbc_service_profit_finish`	decimal(20,6)	COMMENT	'BBC客服经理毛利额_达成',
`bbc_service_target_rate`	decimal(20,6)	COMMENT	'BBC客服经理毛利额_达成率',
`bbc_service_target_rate_tc`	decimal(20,6)	COMMENT	'BBC客服经理毛利额_达成系数',
`tc_sales`	decimal(20,6)	COMMENT	'销售员提成',
`tc_rp_service`	decimal(20,6)	COMMENT	'日配客服经理提成',
`tc_fl_service`	decimal(20,6)	COMMENT	'福利客服经理提成',
`tc_bbc_service`	decimal(20,6)	COMMENT	'BBC客服经理提成',
`update_time`	timestamp	COMMENT    '更新时间',
`smt_ct`	string	COMMENT	'日期分区复制'
) COMMENT '大客户提成-订单明细'
PARTITIONED BY (smt string COMMENT '日期分区')
;


--hive 大客户提成-客户明细
drop table if exists csx_analyse.csx_analyse_fr_tc_customer_detail;
create table csx_analyse.csx_analyse_fr_tc_customer_detail(
`biz_id`	string	COMMENT	'业务主键',
`region_code`	string	COMMENT	'大区编码',
`region_name`	string	COMMENT	'大区',
`province_code`	string	COMMENT	'省区编码',
`province_name`	string	COMMENT	'省区',
`city_group_code`	string	COMMENT	'城市编码',
`city_group_name`	string	COMMENT	'城市',
`customer_code`	string	COMMENT	'客户编码',
`customer_name`	string	COMMENT	'客户名称',
`sales_id`	string	COMMENT	'销售员id',
`work_no`	string	COMMENT	'销售员工号',
`sales_name`	string	COMMENT	'销售员',
`rp_service_user_id`	string	COMMENT	'日配客服经理id',
`rp_service_user_work_no`	string	COMMENT	'日配客服经理工号',
`rp_service_user_name`	string	COMMENT	'日配客服经理',
`fl_service_user_id`	string	COMMENT	'福利客服经理id',
`fl_service_user_work_no`	string	COMMENT	'福利客服经理工号',
`fl_service_user_name`	string	COMMENT	'福利客服经理',
`bbc_service_user_id`	string	COMMENT	'bbc客服经理id',
`bbc_service_user_work_no`	string	COMMENT	'bbc客服经理工号',
`bbc_service_user_name`	string	COMMENT	'bbc客服经理',
`pay_amt`	decimal(20,6)	COMMENT	'回款核销金额',
`rp_pay_amt`	decimal(20,6)	COMMENT	'日配回款金额',
`fl_pay_amt`	decimal(20,6)	COMMENT	'福利回款金额',
`bbc_pay_amt`	decimal(20,6)	COMMENT	'bbc回款金额',
`sales_rp_profit_rate`	decimal(20,6)	COMMENT	'客户日配毛利率-销售员',
`sales_fl_bbc_profit_rate`	decimal(20,6)	COMMENT	'客户福利BBC毛利率-销售员',
`sales_rp_profit_rate_tc`	decimal(20,6)	COMMENT	'客户日配毛利提成比例-销售员',
`sales_fl_bbc_profit_rate_tc`	decimal(20,6)	COMMENT	'客户福利BBC毛利提成比例-销售员',
`rp_service_profit_rate`	decimal(20,6)	COMMENT	'客户日配毛利率-日配客服经理',
`rp_service_profit_rate_tc`	decimal(20,6)	COMMENT	'客户日配毛利提成比例-日配客服经理',
`fl_service_profit_rate`	decimal(20,6)	COMMENT	'客户福利毛利率-福利客服经理',
`fl_service_profit_rate_tc`	decimal(20,6)	COMMENT	'客户福利毛利提成比例-福利客服经理',
`bbc_service_profit_rate`	decimal(20,6)	COMMENT	'客户BBC毛利率-BBC客服经理',
`bbc_service_profit_rate_tc`	decimal(20,6)	COMMENT	'客户BBC毛利提成比例-BBC客服经理',
`rp_sales_fp_rate`	decimal(20,6)	COMMENT	'日配提成系数-销售员',
`fl_sales_sale_fp_rate`	decimal(20,6)	COMMENT	'福利提成系数-销售员',
`bbc_sales_sale_fp_rate`	decimal(20,6)	COMMENT	'BBC提成系数-销售员',
`rp_service_user_fp_rate`	decimal(20,6)	COMMENT	'日配提成系数-日配客服经理',
`fl_service_user_fp_rate`	decimal(20,6)	COMMENT	'福利提成系数-福利客服经理',
`bbc_service_user_fp_rate`	decimal(20,6)	COMMENT	'BBC提成系数-BBC客服经理',
`sales_profit_basic`	decimal(20,6)	COMMENT	'销售员毛利额_基数',
`sales_profit_finish`	decimal(20,6)	COMMENT	'销售员毛利额_达成',
`sales_target_rate`	decimal(20,6)	COMMENT	'销售员毛利额_达成率',
`sales_target_rate_tc`	decimal(20,6)	COMMENT	'销售员毛利额_达成系数',
`rp_service_profit_basic`	decimal(20,6)	COMMENT	'日配客服经理毛利额_基数',
`rp_service_profit_finish`	decimal(20,6)	COMMENT	'日配客服经理毛利额_达成',
`rp_service_target_rate`	decimal(20,6)	COMMENT	'日配客服经理毛利额_达成率',
`rp_service_target_rate_tc`	decimal(20,6)	COMMENT	'日配客服经理毛利额_达成系数',
`fl_service_profit_basic`	decimal(20,6)	COMMENT	'福利客服经理毛利额_基数',
`fl_service_profit_finish`	decimal(20,6)	COMMENT	'福利客服经理毛利额_达成',
`fl_service_target_rate`	decimal(20,6)	COMMENT	'福利客服经理毛利额_达成率',
`fl_service_target_rate_tc`	decimal(20,6)	COMMENT	'福利客服经理毛利额_达成系数',
`bbc_service_profit_basic`	decimal(20,6)	COMMENT	'BBC客服经理毛利额_基数',
`bbc_service_profit_finish`	decimal(20,6)	COMMENT	'BBC客服经理毛利额_达成',
`bbc_service_target_rate`	decimal(20,6)	COMMENT	'BBC客服经理毛利额_达成率',
`bbc_service_target_rate_tc`	decimal(20,6)	COMMENT	'BBC客服经理毛利额_达成系数',
`tc_sales`	decimal(20,6)	COMMENT	'销售员提成',
`tc_rp_service`	decimal(20,6)	COMMENT	'日配客服经理提成',
`tc_fl_service`	decimal(20,6)	COMMENT	'福利客服经理提成',
`tc_bbc_service`	decimal(20,6)	COMMENT	'BBC客服经理提成',
`update_time`	timestamp	COMMENT    '更新时间',
`smt_ct`	string	COMMENT	'日期分区复制'
) COMMENT '大客户提成-客户明细'
PARTITIONED BY (smt string COMMENT '日期分区')
;