-- mysql 保证金看板
CREATE TABLE `csx_tmp_report_sss_incidental_write_off_detail_di` (
`id` 							 bigint(20)     	  NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(32)          NOT NULL  COMMENT    '业务主键',
`region_code`                    varchar(16)          DEFAULT NULL  COMMENT    '大区编码',
`region_name`                    varchar(16)          DEFAULT NULL  COMMENT    '大区名称',
`province_code`                  varchar(16)          DEFAULT NULL  COMMENT    '省份编码',
`province_name`                  varchar(16)          DEFAULT NULL  COMMENT    '省份名称',
`city_group_code`                varchar(16)          DEFAULT NULL  COMMENT    '城市组编码',
`city_group_name`                varchar(16)          DEFAULT NULL  COMMENT    '城市组名称',
`incidental_expenses_no`         varchar(32)          DEFAULT NULL  COMMENT    '杂项用款单号',
`receiving_customer_code`        varchar(32)          DEFAULT NULL  COMMENT    '收款客户编码',
`receiving_customer_name`        varchar(32)          DEFAULT NULL  COMMENT    '收款客户名称',
`first_category_code`            varchar(32)          DEFAULT NULL  COMMENT    '一级客户分类编码',
`first_category_name`            varchar(32)          DEFAULT NULL  COMMENT    '一级客户分类名称',
`second_category_code`           varchar(32)          DEFAULT NULL  COMMENT    '二级客户分类编码',
`second_category_name`           varchar(32)          DEFAULT NULL  COMMENT    '二级客户分类名称',
`third_category_code`            varchar(32)          DEFAULT NULL  COMMENT    '三级客户分类编码',
`third_category_name`            varchar(32)          DEFAULT NULL  COMMENT    '三级客户分类名称',
`custom_category`                varchar(32)          DEFAULT NULL  COMMENT    '自定义分类名称',
`business_scene`                 varchar(16)          DEFAULT NULL  COMMENT    '业务场景名称',
`business_scene_code`            varchar(16)          DEFAULT NULL  COMMENT    '业务场景代码 1:投标保证金  2:履约保证金 3:投标转履约',
`payment_unit_name`              varchar(32)          DEFAULT NULL  COMMENT    '签约主体',
`payment_company_code`           varchar(32)          DEFAULT NULL  COMMENT    '实际付款公司编码',
`payment_company_name`           varchar(32)          DEFAULT NULL  COMMENT    '实际付款公司名称',
`approved_date`                  varchar(32)          DEFAULT NULL  COMMENT    '单据审批通过日期',
`break_contract_date`            varchar(32)          DEFAULT NULL  COMMENT    '断约时间',
`target_payment_time`            varchar(32)          DEFAULT NULL  COMMENT    '目标回款时间',
`account_diff`                   varchar(16)          DEFAULT NULL  COMMENT    '账期天数 断约时间为空取单据审核通过时间',
`account_type`                   varchar(16)          DEFAULT NULL  COMMENT    '账期类型 断约时间为空取单据审核通过时间',
`account_diff2`                  varchar(16)          DEFAULT NULL  COMMENT    '账期天数 断约时间为空不统计',
`account_type2`                  varchar(16)          DEFAULT NULL  COMMENT    '账期类型 断约时间为空不统计',
`payment_amount`                 decimal(20,6)        DEFAULT NULL  COMMENT    '付款金额',
`write_off_amount`               decimal(20,6)        DEFAULT NULL  COMMENT    '核销金额',
`money_back_no_write_off_amount` decimal(20,6)        DEFAULT NULL  COMMENT    '已回款未核销金额',
`lave_write_off_amount`          decimal(20,6)        DEFAULT NULL  COMMENT    '剩余待核销金额',
`lave_write_off_amount_90`       decimal(20,6)        DEFAULT NULL  COMMENT    '90天以上未回款金额',
`lave_write_off_amount_365`      decimal(20,6)        DEFAULT NULL  COMMENT    '1年以上未回款金额',
`create_by`                      varchar(32)          DEFAULT NULL  COMMENT    '创建人',
`create_time`                    datetime             DEFAULT NULL  COMMENT    '创建时间',
`sdt`                            varchar(16)          DEFAULT NULL  COMMENT    '日期分区',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='保证金看板';


