--------------------------------- hive建表语句 -------------------------------
-- csx_tmp.report_sss_r_a_sss_incidental_write_off_info  慧共享保证金

drop table if exists csx_tmp.report_sss_r_a_sss_incidental_write_off_info;
create table csx_tmp.report_sss_r_a_sss_incidental_write_off_info(
`biz_id`                               string         COMMENT    '业务主键',
`region_code`                          string         COMMENT    '大区编码',
`region_name`                          string         COMMENT    '大区名称',
`province_code`                        string         COMMENT    '省份编码',
`province_name`                        string         COMMENT    '省份名称',
`incidental_expenses_no`               string         COMMENT    '杂项用款单号',
`purchase_code`                        string         COMMENT    '所属城市代码',
`purchase_name`                        string         COMMENT    '所属城市名称',
`company_code`                         string         COMMENT    '公司编码',
`company_name`                         string         COMMENT    '公司名称',
`payment_unit_name`                    string         COMMENT    '签约主体',
`payment_company_code`                 string         COMMENT    '实际付款公司编码',
`payment_company_name`                 string         COMMENT    '实际付款公司名称',
`receiving_customer_code`              string         COMMENT    '收款客户编码',
`receiving_customer_name`              string         COMMENT    '收款客户名称',
`business_scene`                       string         COMMENT    '业务场景名称',
`business_scene_code`                  string         COMMENT    '业务场景代码 1:投标保证金  2:履约保证金 3:投标转履约',
`payment_amount`                       string         COMMENT    '付款金额',
`write_off_amount`                     string         COMMENT    '核销金额',
`lave_write_off_amount`                string         COMMENT    '剩余待核销金额',
`payment_status`                       string         COMMENT    '付款状态  S:付款成功 T:已退汇',
`payment_status_name`                  string         COMMENT    '付款状态名称',
`payment_method`                       string         COMMENT    '支付方式  1:外付网银 2:线下',
`payment_method_name`                  string         COMMENT    '支付方式名称',
`apply_user`                           string         COMMENT    '申请人',
`responsible_person`                   string         COMMENT    '负责人',
`write_off_status`                     string         COMMENT    '核销状态  0:未核销  1:已核销 2:部分核销',
`write_off_status_name`                string         COMMENT    '核销状态名称',
`write_off_type`                       string         COMMENT    '核销类型  1:慧共享核销  2:手工核销',
`write_off_type_name`                  string         COMMENT    '核销类型名称',
`apply_date`                           string         COMMENT    '单据申请日期',
`apply_reason`                         string         COMMENT    '申请事由',
`entry_company_code`                   string         COMMENT    '入账单位编码',
`entry_company_name`                   string         COMMENT    '入账单位名称',
`assignment_number`                    string         COMMENT    '分配号',
`audit_status`                         string         COMMENT    '审批状态',
`approved_date`                        string         COMMENT    '单据审批通过日期',
`approved_date2`                       string         COMMENT    '单据审批通过日期2',
`voucher_code`                         string         COMMENT    '凭证编码',
`receiving_account`                    string         COMMENT    '客户收款账号',
`unpaid_progress`                      string         COMMENT    '未回款进度 1:合同未签署 2:退款流程中 3:合同已丢失 4:诉讼中 5:收据已丢失 6:其他',
`unpaid_progress_name`                 string         COMMENT    '未回款进度名称',
`form_todo_progress`                   string         COMMENT    '表单待办进度  0:未填写  1:已完成 2:待办中',
`form_todo_progress_name`              string         COMMENT    '表单待办进度名称',
`finance_form_todo_progress`           string         COMMENT    '财务表单待办进度  0:未填写  1:已完成',
`finance_form_todo_progress_name`      string         COMMENT    '财务表单待办进度名称',
`sale_form_todo_progress`              string         COMMENT    '销售表单待办进度  0:未填写  1:已完成',
`sale_form_todo_progress_name`         string         COMMENT    '销售表单待办进度名称',
`tender_form_todo_progress`            string         COMMENT    '投标表单待办进度  0:未填写  1:已完成',
`tender_form_todo_progress_name`       string         COMMENT    '投标表单待办进度名称',
`attachment_todo_progress`             string         COMMENT    '附件待办进度  0:未上传  1:已完成 2:待办中',
`attachment_todo_progress_name`        string         COMMENT    '附件待办进度名称',
`finance_attachment_todo_progress`     string         COMMENT    '财务附件待办进度  0:未上传  1:已完成',
`finance_attachment_todo_progress_name`string         COMMENT    '财务附件待办进度名称',
`tender_attachment_todo_progress`      string         COMMENT    '投标附件待办进度  0:未上传  1:已完成',
`tender_attachment_todo_progress_name` string         COMMENT    '投标附件待办进名称',
`update_by`                            string         COMMENT    '中台更新人',
`update_time`                          string         COMMENT    '中台更新时间',
`is_deleted`                           string         COMMENT    '状态：0:正常、1:删除',
`self_employed`                        string         COMMENT    '是否自营  0:否  1:是',
`self_employed_name`                   string         COMMENT    '是否自营',
`cooperation_deposit_recovery`         string         COMMENT    '合作保证金是否已收回  0:否  1:是',
`cooperation_deposit_recovery_name`    string         COMMENT    '合作保证金是否已收回',
`money_back_no_write_off`              string         COMMENT    '是否已回款未核销  0:否  1:是',
`money_back_no_write_off_name`         string         COMMENT    '是否已回款未核销',
`change_business_scene`                string         COMMENT    '转其他业务场景',
`change_business_scene_code`           string         COMMENT    '转其他业务场景代码 1:投标保证金  2:履约保证金 3:投标转履约',
`change_performance_offline_voucher`   string         COMMENT    '转履约线下凭证号',
`receipt_recover`                      string         COMMENT    '收据是否回收  0:否  1:是',
`receipt_recover_name`                 string         COMMENT    '收据是否回收',
`contract_recover`                     string         COMMENT    '合同是否回收  0:否  1:是',
`contract_recover_name`                string         COMMENT    '合同是否回收',
`finance_remark`                       string         COMMENT    '财务备注',
`sign_off_attachment_url`              string         COMMENT    '签呈文件附件',
`receipt_attachment_url`               string         COMMENT    '收据文件附件',
`sales_contract_attachment_url`        string         COMMENT    '销售合同文件附件',
`break_contract`                       string         COMMENT    '是否已经断约  0:否  1:是',
`break_contract_name`                  string         COMMENT    '是否已经断约',
`sale_remark`                          string         COMMENT    '销售备注',
`won_bid`                              string         COMMENT    '是否中标',
`won_bid_date`                         string         COMMENT    '中标日期',
`target_payment_time`                  string         COMMENT    '目标回款时间',
`tender_attachment_url`                string         COMMENT    '投标文件附件',
`tender_remark`                        string         COMMENT    '投标备注',
`customer_code`                        string         COMMENT    '客户编码',
`customer_name`                        string         COMMENT    '客户名称',
`operate_no`                           string         COMMENT    '核销单号',
`voucher_no`                           string         COMMENT    'sap凭证单号',
`operate_amount`                       string         COMMENT    '操作金额',
`trade_time`                           string         COMMENT    '交易时间',
`write_off_source`                     string         COMMENT    '核销来源：1:认领、2:冲抵',
`write_off_source_name`                string         COMMENT    '核销来源名称',
`all_write_off`                        string         COMMENT    '是否全部核销：0:否、1:是',
`all_write_off_name`                   string         COMMENT    '是否全部核销',
`operate_type`                         string         COMMENT    '操作类型 0:冲抵中 1:取消占用 2:已执行 3:已释放',
`operate_type_name`                    string         COMMENT    '操作类型名称',
`break_contract_date`                  string         COMMENT    '断约时间',
`receiving_account_name`               string         COMMENT    '收款账号名称',
`account_diff`                         string         COMMENT    '账期天数差值',
`account_type`                         string         COMMENT    '账期类型',
`is_borrow_zizhi`                      string         COMMENT    '是否借资质',
`created_by`                           string         COMMENT    '数据创建人',
`created_time`                         timestamp      COMMENT    '数据创建时间'

) COMMENT '慧共享保证金'
PARTITIONED BY (sdt string COMMENT '日期分区')
STORED AS TEXTFILE tblproperties ("author"="zhangyanpeng");