-- hive 客户合同开票明细
drop table if exists csx_analyse.csx_analyse_fr_customer_contract_invoice_detail_df;
create table csx_analyse.csx_analyse_fr_customer_contract_invoice_detail_df(
`biz_id`	string	COMMENT	'业务主键',
`performance_region_code` string COMMENT '大区编码',
`performance_region_name` string COMMENT '大区名称',
`performance_province_code` string COMMENT '省区编码',
`performance_province_name` string COMMENT '省区名称',
`performance_city_code` string COMMENT '城市编码',
`performance_city_name` string COMMENT '城市名称',
`customer_code` string COMMENT '客户编码',
`customer_name` string COMMENT '客户名称',
`first_category_code` string COMMENT '一级客户分类编码',
`first_category_name` string COMMENT '一级客户分类名称',
`second_category_code` string COMMENT '二级客户分类编码',
`second_category_name` string COMMENT '二级客户分类名称',
`third_category_code` string COMMENT '三级客户分类编码',
`third_category_name` string COMMENT '三级客户分类名称',
`contact_person` string COMMENT '联系人姓名',
`contact_phone` string COMMENT '联系电话',
`company_code` string COMMENT '公司代码',
`company_name` string COMMENT '公司名称',
`wfqyztgsmc` string COMMENT '我方签约主体公司名称',
`khbm` string COMMENT '采购人编码',
`khmc` string COMMENT '采购人名称',
`ywlx` string COMMENT '业务类型',
`thfs` string COMMENT '拓户方式',
`djsqsj` string COMMENT '合同签约时间',
`htbh` string COMMENT '合同编号',
`htqsrq` string COMMENT '合同起始日期',
`htzzrq` string COMMENT '合同终止日期',
`htjey` decimal(20,6) COMMENT '合同金额(元)',
`invoice_date` string COMMENT '开票日期',
`invoice_no` string COMMENT '发票号码',
`invoice_code` string COMMENT '发票代码',
`company_code_invoice` string COMMENT '公司代码',
`total_amount` decimal(20,6) COMMENT '总金额',
`offline_flag` string COMMENT '是否线下开票',
`invoice_remark` string COMMENT '发票备注',
`update_time`	timestamp	COMMENT    '更新时间',
`sdt_ct`	string	COMMENT	'日期分区复制',
`channel_code`	string	COMMENT	'渠道编码',
`channel_name`	string	COMMENT	'渠道名称',
`sales_user_number`	string	COMMENT	'业务员工号',
`sales_user_name`	string	COMMENT	'业务员姓名',
`bloc_code`	string	COMMENT	'集团编码',
`bloc_name`	string	COMMENT	'集团名称',
`invoice_customer_name`	string	COMMENT	'客户开发票名称'
) COMMENT '客户合同开票明细'
PARTITIONED BY (sdt string COMMENT '日期分区')
;


-- hive 客户合同回款明细
drop table if exists csx_analyse.csx_analyse_fr_customer_contract_back_detail_df;
create table csx_analyse.csx_analyse_fr_customer_contract_back_detail_df(
`biz_id`	string	COMMENT	'业务主键',
`performance_region_code` string COMMENT '大区编码',
`performance_region_name` string COMMENT '大区名称',
`performance_province_code` string COMMENT '省区编码',
`performance_province_name` string COMMENT '省区名称',
`performance_city_code` string COMMENT '城市编码',
`performance_city_name` string COMMENT '城市名称',
`customer_code` string COMMENT '客户编码',
`customer_name` string COMMENT '客户名称',
`first_category_code` string COMMENT '一级客户分类编码',
`first_category_name` string COMMENT '一级客户分类名称',
`second_category_code` string COMMENT '二级客户分类编码',
`second_category_name` string COMMENT '二级客户分类名称',
`third_category_code` string COMMENT '三级客户分类编码',
`third_category_name` string COMMENT '三级客户分类名称',
`contact_person` string COMMENT '联系人姓名',
`contact_phone` string COMMENT '联系电话',
`company_code` string COMMENT '公司代码',
`company_name` string COMMENT '公司名称',
`wfqyztgsmc` string COMMENT '我方签约主体公司名称',
`khbm` string COMMENT '采购人编码',
`khmc` string COMMENT '采购人名称',
`ywlx` string COMMENT '业务类型',
`thfs` string COMMENT '拓户方式',
`djsqsj` string COMMENT '合同签约时间',
`htbh` string COMMENT '合同编号',
`htqsrq` string COMMENT '合同起始日期',
`htzzrq` string COMMENT '合同终止日期',
`htjey` decimal(20,6) COMMENT '合同金额(元)',
`claim_date` string COMMENT '回款日期',
`claim_bill_code` string COMMENT '认领单编号',
`company_code_claim` string COMMENT '公司代码',
`profit_center_code` string COMMENT '利润中心',
`credit_code` string COMMENT '信控号',
`claim_amt` decimal(20,6) COMMENT '回单金额',
`summary_text` string COMMENT '摘要文本',
`remark` string COMMENT '备注',
`update_time`	timestamp	COMMENT    '更新时间',
`sdt_ct`	string	COMMENT	'日期分区复制',
`channel_code`	string	COMMENT	'渠道编码',
`channel_name`	string	COMMENT	'渠道名称',
`sales_user_number`	string	COMMENT	'业务员工号',
`sales_user_name`	string	COMMENT	'业务员姓名',
`bloc_code`	string	COMMENT	'集团编码',
`bloc_name`	string	COMMENT	'集团名称'
) COMMENT '客户合同回款明细'
PARTITIONED BY (sdt string COMMENT '日期分区')
;

-- hive 客户合同销售开票回款金额
drop table if exists csx_analyse.csx_analyse_fr_customer_contract_sale_invoice_back_df;
create table csx_analyse.csx_analyse_fr_customer_contract_sale_invoice_back_df(
`biz_id`	string	COMMENT	'业务主键',
`performance_region_code` string COMMENT '大区编码',
`performance_region_name` string COMMENT '大区名称',
`performance_province_code` string COMMENT '省区编码',
`performance_province_name` string COMMENT '省区名称',
`performance_city_code` string COMMENT '城市编码',
`performance_city_name` string COMMENT '城市名称',
`customer_code` string COMMENT '客户编码',
`customer_name` string COMMENT '客户名称',
`first_category_code` string COMMENT '一级客户分类编码',
`first_category_name` string COMMENT '一级客户分类名称',
`second_category_code` string COMMENT '二级客户分类编码',
`second_category_name` string COMMENT '二级客户分类名称',
`third_category_code` string COMMENT '三级客户分类编码',
`third_category_name` string COMMENT '三级客户分类名称',
`contact_person` string COMMENT '联系人姓名',
`contact_phone` string COMMENT '联系电话',
`company_code` string COMMENT '公司代码',
`company_name` string COMMENT '公司名称',
`wfqyztgsmc` string COMMENT '我方签约主体公司名称',
`khbm` string COMMENT '采购人编码',
`khmc` string COMMENT '采购人名称',
`ywlx` string COMMENT '业务类型',
`thfs` string COMMENT '拓户方式',
`djsqsj` string COMMENT '合同签约时间',
`htbh` string COMMENT '合同编号',
`htqsrq` string COMMENT '合同起始日期',
`htzzrq` string COMMENT '合同终止日期',
`htjey` decimal(20,6) COMMENT '合同金额(元)',
`sale_total_amt` string COMMENT '总销售额',
`last_sale_date` string COMMENT '最近销售日期',
`total_amount` decimal(20,6) COMMENT '总开票金额',
`kp_sdt_max` string COMMENT '最近开票日期',
`count_kp` string COMMENT '开票数量',
`claim_amt` decimal(20,6) COMMENT '回单金额',
`claim_sdt_max` string COMMENT '最近回单日期',
`count_claim` string COMMENT '回单数量',
`update_time`	timestamp	COMMENT    '更新时间',
`sdt_ct`	string	COMMENT	'日期分区复制',
`channel_code`	string	COMMENT	'渠道编码',
`channel_name`	string	COMMENT	'渠道名称',
`sales_user_number`	string	COMMENT	'业务员工号',
`sales_user_name`	string	COMMENT	'业务员姓名',
`bloc_code`	string	COMMENT	'集团编码',
`bloc_name`	string	COMMENT	'集团名称',
`invoice_customer_name`	string	COMMENT	'客户开发票名称'
) COMMENT '客户合同销售开票回款金额'
PARTITIONED BY (sdt string COMMENT '日期分区')
;


-- mysql 客户合同开票明细
drop table if exists csx_analyse_fr_customer_contract_invoice_detail_df;	
create table `csx_analyse_fr_customer_contract_invoice_detail_df` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
`biz_id`	varchar(64) NOT NULL DEFAULT '' COMMENT	'业务主键',
`performance_region_code` varchar(64) NOT NULL DEFAULT '' COMMENT '大区编码',
`performance_region_name` varchar(64) NOT NULL DEFAULT '' COMMENT '大区名称',
`performance_province_code` varchar(64) NOT NULL DEFAULT '' COMMENT '省区编码',
`performance_province_name` varchar(64) NOT NULL DEFAULT '' COMMENT '省区名称',
`performance_city_code` varchar(64) NOT NULL DEFAULT '' COMMENT '城市编码',
`performance_city_name` varchar(64) NOT NULL DEFAULT '' COMMENT '城市名称',
`customer_code` varchar(64) NOT NULL DEFAULT '' COMMENT '客户编码',
`customer_name` varchar(128) NOT NULL DEFAULT '' COMMENT '客户名称',
`first_category_code` varchar(64) NOT NULL DEFAULT '' COMMENT '一级客户分类编码',
`first_category_name` varchar(64) NOT NULL DEFAULT '' COMMENT '一级客户分类名称',
`second_category_code` varchar(64) NOT NULL DEFAULT '' COMMENT '二级客户分类编码',
`second_category_name` varchar(64) NOT NULL DEFAULT '' COMMENT '二级客户分类名称',
`third_category_code` varchar(64) NOT NULL DEFAULT '' COMMENT '三级客户分类编码',
`third_category_name` varchar(64) NOT NULL DEFAULT '' COMMENT '三级客户分类名称',
`contact_person` varchar(64) NOT NULL DEFAULT '' COMMENT '联系人姓名',
`contact_phone` varchar(64) NOT NULL DEFAULT '' COMMENT '联系电话',
`company_code` varchar(64) NOT NULL DEFAULT '' COMMENT '公司代码',
`company_name` varchar(64) NOT NULL DEFAULT '' COMMENT '公司名称',
`wfqyztgsmc` varchar(128) NOT NULL DEFAULT '' COMMENT '我方签约主体公司名称',
`khbm` varchar(64) NOT NULL DEFAULT '' COMMENT '采购人编码',
`khmc` varchar(128) NOT NULL DEFAULT '' COMMENT '采购人名称',
`ywlx` varchar(64) NOT NULL DEFAULT '' COMMENT '业务类型',
`thfs` varchar(64) NOT NULL DEFAULT '' COMMENT '拓户方式',
`djsqsj` varchar(64) NOT NULL DEFAULT '' COMMENT '合同签约时间',
`htbh` varchar(64) NOT NULL DEFAULT '' COMMENT '合同编号',
`htqsrq` varchar(64) NOT NULL DEFAULT '' COMMENT '合同起始日期',
`htzzrq` varchar(64) NOT NULL DEFAULT '' COMMENT '合同终止日期',
`htjey` decimal(20,6) COMMENT '合同金额(元)',
`invoice_date` varchar(64) NOT NULL DEFAULT '' COMMENT '开票日期',
`invoice_no` varchar(64) NOT NULL DEFAULT '' COMMENT '发票号码',
`invoice_code` varchar(64) NOT NULL DEFAULT '' COMMENT '发票代码',
`company_code_invoice` varchar(64) NOT NULL DEFAULT '' COMMENT '公司代码',
`total_amount` decimal(20,6) COMMENT '总金额',
`offline_flag` varchar(64) NOT NULL DEFAULT '' COMMENT '是否线下开票',
`invoice_remark` varchar(1024) NOT NULL DEFAULT '' COMMENT '发票备注',
`update_time`	timestamp	COMMENT    '更新时间',
`sdt_ct`	varchar(64) NOT NULL DEFAULT '' COMMENT	'日期分区复制',
`channel_code` varchar(64) NOT NULL DEFAULT '' COMMENT '渠道编码',
`channel_name` varchar(64) NOT NULL DEFAULT '' COMMENT '渠道名称',
`sales_user_number` varchar(64) NOT NULL DEFAULT '' COMMENT '业务员工号',
`sales_user_name` varchar(64) NOT NULL DEFAULT '' COMMENT '业务员姓名',
`bloc_code` varchar(64) NOT NULL DEFAULT '' COMMENT '集团编码',
`bloc_name` varchar(128) NOT NULL DEFAULT '' COMMENT '集团名称',
`invoice_customer_name` varchar(128) NOT NULL DEFAULT '' COMMENT '客户开发票名称',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='客户合同开票明细';


-- mysql 客户合同回款明细
drop table if exists csx_analyse_fr_customer_contract_back_detail_df;	
create table `csx_analyse_fr_customer_contract_back_detail_df` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
`biz_id`	varchar(64) NOT NULL DEFAULT '' COMMENT	'业务主键',
`performance_region_code` varchar(64) NOT NULL DEFAULT '' COMMENT '大区编码',
`performance_region_name` varchar(64) NOT NULL DEFAULT '' COMMENT '大区名称',
`performance_province_code` varchar(64) NOT NULL DEFAULT '' COMMENT '省区编码',
`performance_province_name` varchar(64) NOT NULL DEFAULT '' COMMENT '省区名称',
`performance_city_code` varchar(64) NOT NULL DEFAULT '' COMMENT '城市编码',
`performance_city_name` varchar(64) NOT NULL DEFAULT '' COMMENT '城市名称',
`customer_code` varchar(64) NOT NULL DEFAULT '' COMMENT '客户编码',
`customer_name` varchar(128) NOT NULL DEFAULT '' COMMENT '客户名称',
`first_category_code` varchar(64) NOT NULL DEFAULT '' COMMENT '一级客户分类编码',
`first_category_name` varchar(64) NOT NULL DEFAULT '' COMMENT '一级客户分类名称',
`second_category_code` varchar(64) NOT NULL DEFAULT '' COMMENT '二级客户分类编码',
`second_category_name` varchar(64) NOT NULL DEFAULT '' COMMENT '二级客户分类名称',
`third_category_code` varchar(64) NOT NULL DEFAULT '' COMMENT '三级客户分类编码',
`third_category_name` varchar(64) NOT NULL DEFAULT '' COMMENT '三级客户分类名称',
`contact_person` varchar(64) NOT NULL DEFAULT '' COMMENT '联系人姓名',
`contact_phone` varchar(64) NOT NULL DEFAULT '' COMMENT '联系电话',
`company_code` varchar(64) NOT NULL DEFAULT '' COMMENT '公司代码',
`company_name` varchar(64) NOT NULL DEFAULT '' COMMENT '公司名称',
`wfqyztgsmc` varchar(128) NOT NULL DEFAULT '' COMMENT '我方签约主体公司名称',
`khbm` varchar(64) NOT NULL DEFAULT '' COMMENT '采购人编码',
`khmc` varchar(128) NOT NULL DEFAULT '' COMMENT '采购人名称',
`ywlx` varchar(64) NOT NULL DEFAULT '' COMMENT '业务类型',
`thfs` varchar(64) NOT NULL DEFAULT '' COMMENT '拓户方式',
`djsqsj` varchar(64) NOT NULL DEFAULT '' COMMENT '合同签约时间',
`htbh` varchar(64) NOT NULL DEFAULT '' COMMENT '合同编号',
`htqsrq` varchar(64) NOT NULL DEFAULT '' COMMENT '合同起始日期',
`htzzrq` varchar(64) NOT NULL DEFAULT '' COMMENT '合同终止日期',
`htjey` decimal(20,6) COMMENT '合同金额(元)',
`claim_date` varchar(64) NOT NULL DEFAULT '' COMMENT '回款日期',
`claim_bill_code` varchar(64) NOT NULL DEFAULT '' COMMENT '认领单编号',
`company_code_claim` varchar(64) NOT NULL DEFAULT '' COMMENT '公司代码',
`profit_center_code` varchar(64) NOT NULL DEFAULT '' COMMENT '利润中心',
`credit_code` varchar(64) NOT NULL DEFAULT '' COMMENT '信控号',
`claim_amt` decimal(20,6) COMMENT '回单金额',
`summary_text` varchar(1024) NOT NULL DEFAULT '' COMMENT '摘要文本',
`remark` varchar(1024) NOT NULL DEFAULT '' COMMENT '备注',
`update_time`	timestamp	COMMENT    '更新时间',
`sdt_ct`	varchar(64) NOT NULL DEFAULT '' COMMENT	'日期分区复制',
`channel_code` varchar(64) NOT NULL DEFAULT '' COMMENT '渠道编码',
`channel_name` varchar(64) NOT NULL DEFAULT '' COMMENT '渠道名称',
`sales_user_number` varchar(64) NOT NULL DEFAULT '' COMMENT '业务员工号',
`sales_user_name` varchar(64) NOT NULL DEFAULT '' COMMENT '业务员姓名',
`bloc_code` varchar(64) NOT NULL DEFAULT '' COMMENT '集团编码',
`bloc_name` varchar(128) NOT NULL DEFAULT '' COMMENT '集团名称',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='客户合同回款明细';


-- mysql 客户合同销售开票回款金额
drop table if exists csx_analyse_fr_customer_contract_sale_invoice_back_df;	
create table `csx_analyse_fr_customer_contract_sale_invoice_back_df` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
`biz_id`	varchar(64) NOT NULL DEFAULT '' COMMENT	'业务主键',
`performance_region_code` varchar(64) NOT NULL DEFAULT '' COMMENT '大区编码',
`performance_region_name` varchar(64) NOT NULL DEFAULT '' COMMENT '大区名称',
`performance_province_code` varchar(64) NOT NULL DEFAULT '' COMMENT '省区编码',
`performance_province_name` varchar(64) NOT NULL DEFAULT '' COMMENT '省区名称',
`performance_city_code` varchar(64) NOT NULL DEFAULT '' COMMENT '城市编码',
`performance_city_name` varchar(64) NOT NULL DEFAULT '' COMMENT '城市名称',
`customer_code` varchar(64) NOT NULL DEFAULT '' COMMENT '客户编码',
`customer_name` varchar(128) NOT NULL DEFAULT '' COMMENT '客户名称',
`first_category_code` varchar(64) NOT NULL DEFAULT '' COMMENT '一级客户分类编码',
`first_category_name` varchar(64) NOT NULL DEFAULT '' COMMENT '一级客户分类名称',
`second_category_code` varchar(64) NOT NULL DEFAULT '' COMMENT '二级客户分类编码',
`second_category_name` varchar(64) NOT NULL DEFAULT '' COMMENT '二级客户分类名称',
`third_category_code` varchar(64) NOT NULL DEFAULT '' COMMENT '三级客户分类编码',
`third_category_name` varchar(64) NOT NULL DEFAULT '' COMMENT '三级客户分类名称',
`contact_person` varchar(64) NOT NULL DEFAULT '' COMMENT '联系人姓名',
`contact_phone` varchar(64) NOT NULL DEFAULT '' COMMENT '联系电话',
`company_code` varchar(64) NOT NULL DEFAULT '' COMMENT '公司代码',
`company_name` varchar(64) NOT NULL DEFAULT '' COMMENT '公司名称',
`wfqyztgsmc` varchar(128) NOT NULL DEFAULT '' COMMENT '我方签约主体公司名称',
`khbm` varchar(64) NOT NULL DEFAULT '' COMMENT '采购人编码',
`khmc` varchar(128) NOT NULL DEFAULT '' COMMENT '采购人名称',
`ywlx` varchar(64) NOT NULL DEFAULT '' COMMENT '业务类型',
`thfs` varchar(64) NOT NULL DEFAULT '' COMMENT '拓户方式',
`djsqsj` varchar(64) NOT NULL DEFAULT '' COMMENT '合同签约时间',
`htbh` varchar(64) NOT NULL DEFAULT '' COMMENT '合同编号',
`htqsrq` varchar(64) NOT NULL DEFAULT '' COMMENT '合同起始日期',
`htzzrq` varchar(64) NOT NULL DEFAULT '' COMMENT '合同终止日期',
`htjey` decimal(20,6) COMMENT '合同金额(元)',
`sale_total_amt` varchar(64) NOT NULL DEFAULT '' COMMENT '总销售额',
`last_sale_date` varchar(64) NOT NULL DEFAULT '' COMMENT '最近销售日期',
`total_amount` decimal(20,6) COMMENT '总开票金额',
`kp_sdt_max` varchar(64) NOT NULL DEFAULT '' COMMENT '最近开票日期',
`count_kp` varchar(64) NOT NULL DEFAULT '' COMMENT '开票数量',
`claim_amt` decimal(20,6) COMMENT '回单金额',
`claim_sdt_max` varchar(64) NOT NULL DEFAULT '' COMMENT '最近回单日期',
`count_claim` varchar(64) NOT NULL DEFAULT '' COMMENT '回单数量',
`update_time`	timestamp	COMMENT    '更新时间',
`sdt_ct`	varchar(64) NOT NULL DEFAULT '' COMMENT	'日期分区复制',
`channel_code` varchar(64) NOT NULL DEFAULT '' COMMENT '渠道编码',
`channel_name` varchar(64) NOT NULL DEFAULT '' COMMENT '渠道名称',
`sales_user_number` varchar(64) NOT NULL DEFAULT '' COMMENT '业务员工号',
`sales_user_name` varchar(64) NOT NULL DEFAULT '' COMMENT '业务员姓名',
`bloc_code` varchar(64) NOT NULL DEFAULT '' COMMENT '集团编码',
`bloc_name` varchar(128) NOT NULL DEFAULT '' COMMENT '集团名称',
`invoice_customer_name` varchar(128) NOT NULL DEFAULT '' COMMENT '客户开发票名称',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='客户合同销售开票回款金额';


truncate csx_analyse_fr_customer_contract_invoice_detail_df;
truncate csx_analyse_fr_customer_contract_back_detail_df;
truncate csx_analyse_fr_customer_contract_sale_invoice_back_df;


