-- mysql
CREATE TABLE `csx_analyse_report_oms_bulletin_board_complaint_di` (
`id` 							 bigint(20)     	  NOT NULL AUTO_INCREMENT COMMENT '主键',
`performance_region_code`        varchar(32)         DEFAULT NULL  COMMENT    '大区编码',
`performance_region_name`        varchar(32)         DEFAULT NULL  COMMENT    '大区名称',
`performance_province_code`      varchar(32)         DEFAULT NULL  COMMENT    '省区编码',
`performance_province_name`      varchar(32)         DEFAULT NULL  COMMENT    '省区名称',
`performance_city_code`          varchar(32)         DEFAULT NULL  COMMENT    '城市编码',
`performance_city_name`          varchar(32)         DEFAULT NULL  COMMENT    '城市名称',
`complaint_no`                   varchar(64)         DEFAULT NULL  COMMENT    '客诉单号',
`order_no`                       varchar(64)         DEFAULT NULL  COMMENT    '销售单号',
`complaint_date`                 varchar(32)         DEFAULT NULL  COMMENT    '创建日期',
`complaint_status`               int                 DEFAULT NULL  COMMENT    '投诉状态',
`complaint_status_name`          varchar(32)         DEFAULT NULL  COMMENT    '投诉状态名称',
`complaint_deal_status`          int                 DEFAULT NULL  COMMENT    '客诉处理状态',
`complaint_deal_status_name`     varchar(32)         DEFAULT NULL  COMMENT    '客诉处理状态名称',
`complaint_type_code`            varchar(32)         DEFAULT NULL  COMMENT    '客诉类型编码(小类)',
`complaint_type_name`            varchar(32)         DEFAULT NULL  COMMENT    '客诉类型',
`channel_type`                   int                 DEFAULT NULL  COMMENT    '渠道 1-OMS 2-CRM',
`work_no`                        varchar(32)         DEFAULT NULL  COMMENT    '业务员工号',
`sales_name`                     varchar(32)         DEFAULT NULL  COMMENT    '业务员名称',
`customer_no`                    varchar(32)         DEFAULT NULL  COMMENT    '客户编码',
`customer_name`                  varchar(64)         DEFAULT NULL  COMMENT    '客户名称',
`sub_customer_code`              varchar(32)         DEFAULT NULL  COMMENT    '子客户编码',
`sub_customer_name`              varchar(64)         DEFAULT NULL  COMMENT    '子客户名称',
`main_category_code`             varchar(32)         DEFAULT NULL  COMMENT    '客诉大类编码',
`main_category_name`             varchar(32)         DEFAULT NULL  COMMENT    '客诉大类名称',
`sub_category_code`              varchar(32)         DEFAULT NULL  COMMENT    '客诉小类编码',
`sub_category_name`              varchar(32)         DEFAULT NULL  COMMENT    '客诉小类名称',
`goods_code`                     varchar(32)         DEFAULT NULL  COMMENT    '商品编码',
`goods_name`                     varchar(64)         DEFAULT NULL  COMMENT    '商品名称',
`responsible_department_code`    varchar(32)         DEFAULT NULL  COMMENT    '责任(二级)部门编码',
`responsible_department_name`    varchar(64)         DEFAULT NULL  COMMENT    '责任部门名称',
`responsible_person_id`          varchar(32)         DEFAULT NULL  COMMENT    '责任人id',
`responsible_person_name`        varchar(64)         DEFAULT NULL  COMMENT    '责任人姓名',
`deal_date`                      varchar(32)         DEFAULT NULL  COMMENT    '处理日期',
`node_code`                      varchar(32)         DEFAULT NULL  COMMENT    '客诉环节编码',
`node_name`                      varchar(64)         DEFAULT NULL  COMMENT    '客诉环节名称',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='共享中心客诉看板-客诉部分';