--服务管家提成表
drop table if exists csx_dw.report_sss_r_m_crm_service_commission;
create table csx_dw.report_sss_r_m_crm_service_commission(
`biz_id`                         string              COMMENT    '业务主键',
`region_code`                    string              COMMENT    '大区编码',
`region_name`                    string              COMMENT    '大区名称',
`province_code`                  string              COMMENT    '省区编码',
`province_name`                  string              COMMENT    '省区名称',
`city_group_code`                string              COMMENT    '城市组编码',
`city_group_name`                string              COMMENT    '城市组名称',
`yearmonth`                      string              COMMENT    '年月',
`service_id`                     string              COMMENT    '服务管家ID',
`service_work_no`                string              COMMENT    '服务管家工号',
`service_name`                   string              COMMENT    '服务管家名称',
`sales_value`                    decimal(20,6)       COMMENT    '销售额',
`ripei_sales_value`              decimal(20,6)       COMMENT    '日配销售额',
`bbc_sales_value`                decimal(20,6)       COMMENT    'BBC销售额',
`fuli_sales_value`               decimal(20,6)       COMMENT    '福利销售额',
`ripei_bbc_sales_value`          decimal(20,6)       COMMENT    '日配&BBC销售额',
`profit`                         decimal(20,6)       COMMENT    '定价毛利额',
`ripei_profit`                   decimal(20,6)       COMMENT    '日配定价毛利额',
`bbc_profit`                     decimal(20,6)       COMMENT    'BBC定价毛利额',
`fuli_profit`                    decimal(20,6)       COMMENT    '福利定价毛利额',
`ripei_bbc_profit`               decimal(20,6)       COMMENT    '日配&BBC定价毛利额',
`prorate`                        decimal(20,6)       COMMENT    '定价毛利率',
`ripei_prorate`                  decimal(20,6)       COMMENT    '日配定价毛利率',
`bbc_prorate`                    decimal(20,6)       COMMENT    'BBC定价毛利率',
`fuli_prorate`                   decimal(20,6)       COMMENT    '福利定价毛利率',
`ripei_bbc_prorate`              decimal(20,6)       COMMENT    '日配&bbc定价毛利率',
`salary_sales_value`             decimal(20,6)       COMMENT    '奖金包_销售额',
`salary_profit`                  decimal(20,6)       COMMENT    '奖金包_定价毛利额',
`receivable_amount`              decimal(20,6)       COMMENT    '应收金额',
`overdue_amount`                 decimal(20,6)       COMMENT    '逾期金额',
`service_over_rate`              decimal(20,6)       COMMENT    '逾期系数',
`tc_sales_value`                 decimal(20,6)       COMMENT    '提成_销售额',
`tc_profit`                      decimal(20,6)       COMMENT    '提成_定价毛利额',
`tc_total`                       decimal(20,6)       COMMENT    '总提成',
`create_by`                      string              COMMENT    '创建人',
`create_time`                    timestamp           COMMENT    '创建时间',
`update_time`                    timestamp           COMMENT    '更新时间'

) COMMENT '服务管家提成表'
PARTITIONED BY (sdt string COMMENT '提成日期分区')
STORED AS TEXTFILE;


--销售员提成表
drop table if exists csx_dw.report_sss_r_m_crm_salesperson_commission;
create table csx_dw.report_sss_r_m_crm_salesperson_commission(
`biz_id`                         string              COMMENT    '业务主键',
`region_code`                    string              COMMENT    '大区编码',
`region_name`                    string              COMMENT    '大区名称',
`province_code`                  string              COMMENT    '省区编码',
`province_name`                  string              COMMENT    '省区名称',
`city_group_code`                string              COMMENT    '城市组编码',
`city_group_name`                string              COMMENT    '城市组名称',
`yearmonth`                      string              COMMENT    '年月',
`sales_id`                       string              COMMENT    '销售员ID',
`work_no`                        string              COMMENT    '销售员工号',
`sales_name`                     string              COMMENT    '销售员名称',
`sales_value_ytd`                decimal(20,6)       COMMENT    '销售额_年至今',
`ripei_bbc_sales_value_ytd`      decimal(20,6)       COMMENT    '日配&BBC销售额_年至今',
`fuli_sales_value_ytd`           decimal(20,6)       COMMENT    '福利销售额_年至今',
`sales_value`                    decimal(20,6)       COMMENT    '销售额',
`ripei_sales_value`              decimal(20,6)       COMMENT    '日配销售额',
`bbc_sales_value`                decimal(20,6)       COMMENT    'BBC销售额',
`fuli_sales_value`               decimal(20,6)       COMMENT    '福利销售额',
`ripei_bbc_sales_value`          decimal(20,6)       COMMENT    '日配&BBC销售额',
`profit`                         decimal(20,6)       COMMENT    '定价毛利额',
`ripei_profit`                   decimal(20,6)       COMMENT    '日配定价毛利额',
`bbc_profit`                     decimal(20,6)       COMMENT    'BBC定价毛利额',
`fuli_profit`                    decimal(20,6)       COMMENT    '福利定价毛利额',
`ripei_bbc_profit`               decimal(20,6)       COMMENT    '日配&BBC定价毛利额',
`prorate`                        decimal(20,6)       COMMENT    '定价毛利率',
`ripei_prorate`                  decimal(20,6)       COMMENT    '日配定价毛利率',
`bbc_prorate`                    decimal(20,6)       COMMENT    'BBC定价毛利率',
`fuli_prorate`                   decimal(20,6)       COMMENT    '福利定价毛利率',
`ripei_bbc_prorate`              decimal(20,6)       COMMENT    '日配&bbc定价毛利率',
`salary_fuli_sales_value`        decimal(20,6)       COMMENT    '奖金包_福利销售额',
`salary_fuli_profit`             decimal(20,6)       COMMENT    '奖金包_福利定价毛利额',
`salary_ripei_sales_value`       decimal(20,6)       COMMENT    '奖金包_日配销售额',
`salary_ripei_profit`            decimal(20,6)       COMMENT    '奖金包_日配定价毛利额',
`salary_bbc_sales_value`         decimal(20,6)       COMMENT    '奖金包_BBC销售额',
`salary_bbc_profit`              decimal(20,6)       COMMENT    '奖金包_BBC定价毛利额',
`salary_ripei_bbc_sales_value`   decimal(20,6)       COMMENT    '奖金包_日配&BBC销售额',
`salary_ripei_bbc_profit`        decimal(20,6)       COMMENT    '奖金包_日配&BBC定价毛利额',
`receivable_amount`              decimal(20,6)       COMMENT    '应收金额',
`overdue_amount`                 decimal(20,6)       COMMENT    '逾期金额',
`salesperson_over_rate`          decimal(20,6)       COMMENT    '逾期系数',
`tc_sales_value`                 decimal(20,6)       COMMENT    '提成_销售额',
`tc_profit`                      decimal(20,6)       COMMENT    '提成_定价毛利额',
`tc_total`                       decimal(20,6)       COMMENT    '总提成',
`create_by`                      string              COMMENT    '创建人',
`create_time`                    timestamp           COMMENT    '创建时间',
`update_time`                    timestamp           COMMENT    '更新时间'

) COMMENT '销售员提成表'
PARTITIONED BY (sdt string COMMENT '提成日期分区')
STORED AS TEXTFILE;


--客户提成表
drop table if exists csx_dw.report_sss_r_m_crm_customer_commission;
create table csx_dw.report_sss_r_m_crm_customer_commission(
`biz_id`                             string              COMMENT    '业务主键',
`region_code`                        string              COMMENT    '大区编码',
`region_name`                        string              COMMENT    '大区名称',
`province_code`                      string              COMMENT    '省区编码',
`province_name`                      string              COMMENT    '省区名称',
`city_group_code`                    string              COMMENT    '城市组编码',
`city_group_name`                    string              COMMENT    '城市组名称',
`yearmonth`                          string              COMMENT    '年月',
`customer_id`                        string              COMMENT    '客户ID',
`customer_no`                        string              COMMENT    '客户编号',
`customer_name`                      string              COMMENT    '客户名称',
`sales_id`                           string              COMMENT    '销售员ID',
`work_no`                            string              COMMENT    '销售员工号',
`sales_name`                         string              COMMENT    '销售员名称',
`is_part_time_service_manager`       string              COMMENT    '销售员是否兼岗服务管家',
`service_id`                         string              COMMENT    '服务管家ID',
`service_work_no`                    string              COMMENT    '服务管家工号',
`service_name`                       string              COMMENT    '服务管家名称',
`sales_value`                        decimal(20,6)       COMMENT    '销售额',
`ripei_sales_value`                  decimal(20,6)       COMMENT    '日配销售额',
`bbc_sales_value`                    decimal(20,6)       COMMENT    'BBC销售额',
`fuli_sales_value`                   decimal(20,6)       COMMENT    '福利销售额',
`ripei_bbc_sales_value`              decimal(20,6)       COMMENT    '日配&BBC销售额',
`profit`                             decimal(20,6)       COMMENT    '定价毛利额',
`ripei_profit`                       decimal(20,6)       COMMENT    '日配定价毛利额',
`bbc_profit`                         decimal(20,6)       COMMENT    'BBC定价毛利额',
`fuli_profit`                        decimal(20,6)       COMMENT    '福利定价毛利额',
`ripei_bbc_profit`                   decimal(20,6)       COMMENT    '日配&BBC定价毛利额',
`prorate`                            decimal(20,6)       COMMENT    '定价毛利率',
`ripei_prorate`                      decimal(20,6)       COMMENT    '日配定价毛利率',
`bbc_prorate`                        decimal(20,6)       COMMENT    'BBC定价毛利率',
`fuli_prorate`                       decimal(20,6)       COMMENT    '福利定价毛利率',
`ripei_bbc_prorate`                  decimal(20,6)       COMMENT    '日配&bbc定价毛利率',
`salesperson_ripei_bbc_prorate`      decimal(20,6)       COMMENT    '销售员日配&bbc定价毛利率',
`salesperson_fuli_prorate`           decimal(20,6)       COMMENT    '销售员福利定价毛利率',
`salary_fuli_sales_value`            decimal(20,6)       COMMENT    '奖金包_福利销售额',
`salary_fuli_profit`                 decimal(20,6)       COMMENT    '奖金包_福利定价毛利额',
`salary_ripei_sales_value`           decimal(20,6)       COMMENT    '奖金包_日配销售额',
`salary_ripei_profit`                decimal(20,6)       COMMENT    '奖金包_日配定价毛利额',
`salary_bbc_sales_value`             decimal(20,6)       COMMENT    '奖金包_BBC销售额',
`salary_bbc_profit`                  decimal(20,6)       COMMENT    '奖金包_BBC定价毛利额',
`salary_ripei_bbc_sales_value`       decimal(20,6)       COMMENT    '奖金包_日配&BBC销售额',
`salary_ripei_bbc_profit`            decimal(20,6)       COMMENT    '奖金包_日配&BBC定价毛利额',
`receivable_amount`                  decimal(20,6)       COMMENT    '应收金额',
`overdue_amount`                     decimal(20,6)       COMMENT    '逾期金额',
`assigned_type`                      decimal(20,6)       COMMENT    '分配类别',
`salesperson_sales_value_fp_rate`    decimal(20,6)       COMMENT    '销售员销售额分配比例',
`salesperson_profit_fp_rate`         decimal(20,6)       COMMENT    '销售员定价毛利额分配比例',
`service_sales_value_fp_rate`        decimal(20,6)       COMMENT    '服务管家销售额分配比例',
`service_profit_fp_rate`             decimal(20,6)       COMMENT    '服务管家定价毛利额分配比例',
`salesperson_over_rate`              decimal(20,6)       COMMENT    '销售员逾期系数',
`service_over_rate`                  decimal(20,6)       COMMENT    '服务管家逾期系数',
`tc_ripei_sales_value_salesperson`   decimal(20,6)       COMMENT    '提成_销售员_销售额',
`tc_sales_value_service`             decimal(20,6)       COMMENT    '提成_服务管家_销售额',
`tc_ripei_profit_salesperson`        decimal(20,6)       COMMENT    '提成_销售员_定价毛利额',
`tc_profit_service`                  decimal(20,6)       COMMENT    '提成_服务管家_定价毛利额',
`tc_salesperson`                     decimal(20,6)       COMMENT    '提成_销售员',
`tc_service`                         decimal(20,6)       COMMENT    '提成_服务管家',
`create_by`                          string              COMMENT    '创建人',
`create_time`                        timestamp           COMMENT    '创建时间',
`update_time`                        timestamp           COMMENT    '更新时间'

) COMMENT '客户提成表'
PARTITIONED BY (sdt string COMMENT '提成日期分区')
STORED AS TEXTFILE;


--客户逾期表
drop table if exists csx_dw.report_sss_r_m_crm_customer_over_rate;
create table csx_dw.report_sss_r_m_crm_customer_over_rate(
`biz_id`                             string              COMMENT    '业务主键',
`region_code`                        string              COMMENT    '大区编码',
`region_name`                        string              COMMENT    '大区名称',
`province_code`                      string              COMMENT    '省区编码',
`province_name`                      string              COMMENT    '省区名称',
`city_group_code`                    string              COMMENT    '城市组编码',
`city_group_name`                    string              COMMENT    '城市组名称',
`yearmonth`                          string              COMMENT    '年月',
`channel_code`                       string              COMMENT    '渠道编码',
`channel_name`                       string              COMMENT    '渠道名称',
`customer_id`                        string              COMMENT    '客户ID',
`customer_no`                        string              COMMENT    '客户编号',
`customer_name`                      string              COMMENT    '客户名称',
`sales_id`                           string              COMMENT    '销售员ID',
`work_no`                            string              COMMENT    '销售员工号',
`sales_name`                         string              COMMENT    '销售员名称',
`service_id`                         string              COMMENT    '服务管家ID',
`service_work_no`                    string              COMMENT    '服务管家工号',
`service_name`                       string              COMMENT    '服务管家名称',
`is_part_time_service_manager`       string              COMMENT    '销售员是否兼岗服务管家',
`payment_terms`                      string              COMMENT    '账期类型',
`payment_days`                       int                 COMMENT    '账期天数',
`payment_name`                       string              COMMENT    '账期名称',
`company_code`                       string              COMMENT    '公司编码',
`company_name`                       string              COMMENT    '公司名称',
`receivable_amount`                  decimal(20,6)       COMMENT    '应收金额',
`overdue_amount`                     decimal(20,6)       COMMENT    '逾期金额',
`overdue_coefficient_numerator`      decimal(20,6)       COMMENT    '逾期金额*逾期天数',
`overdue_coefficient_denominator`    decimal(20,6)       COMMENT    '应收金额*帐期天数',
`over_rate`                          decimal(20,6)       COMMENT    '逾期系数',
`is_greater_0`                       string              COMMENT    '应收大于0',
`create_by`                          string              COMMENT    '创建人',
`create_time`                        timestamp           COMMENT    '创建时间',
`update_time`                        timestamp           COMMENT    '更新时间'

) COMMENT '客户逾期表'
PARTITIONED BY (sdt string COMMENT '日期分区')
STORED AS TEXTFILE;
