--服务管家提成表
CREATE TABLE `report_sss_r_m_crm_service_commission` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(50)          NOT NULL  COMMENT    '业务主键',
`region_code`                    varchar(16)          not NULL COMMENT    '大区编码',
`region_name`                    varchar(16)          not NULL COMMENT    '大区名称',
`province_code`                  varchar(16)          not NULL COMMENT    '省区编码',
`province_name`                  varchar(16)          not NULL COMMENT    '省区名称',
`city_group_code`                varchar(16)          not NULL COMMENT    '城市组编码',
`city_group_name`                varchar(16)          not NULL COMMENT    '城市组名称',
`yearmonth`                      varchar(16)          not NULL COMMENT    '年月',
`service_id`                     varchar(16)          not NULL COMMENT    '服务管家ID',
`service_work_no`                varchar(16)          not NULL COMMENT    '服务管家工号',
`service_name`                   varchar(16)          not NULL COMMENT    '服务管家名称',
`sales_value`                    decimal(20,6)        DEFAULT NULL COMMENT    '销售额',
`ripei_sales_value`              decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额',
`bbc_sales_value`                decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额',
`fuli_sales_value`               decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额',
`ripei_bbc_sales_value`          decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额',
`profit`                         decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额',
`ripei_profit`                   decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额',
`bbc_profit`                     decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额',
`fuli_profit`                    decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额',
`ripei_bbc_profit`               decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额',
`prorate`                        decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利率',
`ripei_prorate`                  decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利率',
`bbc_prorate`                    decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利率',
`fuli_prorate`                   decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利率',
`ripei_bbc_prorate`              decimal(20,6)        DEFAULT NULL COMMENT    '日配&bbc定价毛利率',
`salary_sales_value`             decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_销售额',
`salary_profit`                  decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_定价毛利额',
`receivable_amount`              decimal(20,6)        DEFAULT NULL COMMENT    '应收金额',
`overdue_amount`                 decimal(20,6)        DEFAULT NULL COMMENT    '逾期金额',
`service_over_rate`              decimal(20,6)        DEFAULT NULL COMMENT    '逾期系数',
`tc_sales_value`                 decimal(20,6)        DEFAULT NULL COMMENT    '提成_销售额',
`tc_profit`                      decimal(20,6)        DEFAULT NULL COMMENT    '提成_定价毛利额',
`tc_total`                       decimal(20,6)        DEFAULT NULL COMMENT    '总提成',
`create_by`                      varchar(64)          DEFAULT NULL COMMENT    '创建人',
`create_time`                    datetime             DEFAULT NULL COMMENT    '创建时间',
`update_time`                    datetime             DEFAULT NULL COMMENT    '更新时间',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT    '统计日期',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务管家提成表';


--销售员提成表
CREATE TABLE `report_sss_r_m_crm_salesperson_commission` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(50)          NOT NULL  COMMENT    '业务主键',
`region_code`                    varchar(16)          not NULL COMMENT    '大区编码',
`region_name`                    varchar(16)          not NULL COMMENT    '大区名称',
`province_code`                  varchar(16)          not NULL COMMENT    '省区编码',
`province_name`                  varchar(16)          not NULL COMMENT    '省区名称',
`city_group_code`                varchar(16)          not NULL COMMENT    '城市组编码',
`city_group_name`                varchar(16)          not NULL COMMENT    '城市组名称',
`yearmonth`                      varchar(16)          not NULL COMMENT    '年月',
`sales_id`                       varchar(16)          not NULL COMMENT    '销售员ID',
`work_no`                        varchar(16)          not NULL COMMENT    '销售员工号',
`sales_name`                     varchar(16)          not NULL COMMENT    '销售员名称',
`sales_value_ytd`                decimal(20,6)        DEFAULT NULL COMMENT    '销售额_年至今',
`ripei_bbc_sales_value_ytd`      decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额_年至今',
`fuli_sales_value_ytd`           decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额_年至今',
`sales_value`                    decimal(20,6)        DEFAULT NULL COMMENT    '销售额',
`ripei_sales_value`              decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额',
`bbc_sales_value`                decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额',
`fuli_sales_value`               decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额',
`ripei_bbc_sales_value`          decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额',
`profit`                         decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额',
`ripei_profit`                   decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额',
`bbc_profit`                     decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额',
`fuli_profit`                    decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额',
`ripei_bbc_profit`               decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额',
`prorate`                        decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利率',
`ripei_prorate`                  decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利率',
`bbc_prorate`                    decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利率',
`fuli_prorate`                   decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利率',
`ripei_bbc_prorate`              decimal(20,6)        DEFAULT NULL COMMENT    '日配&bbc定价毛利率',
`salary_fuli_sales_value`        decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_福利销售额',
`salary_fuli_profit`             decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_福利定价毛利额',
`salary_ripei_sales_value`       decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_日配销售额',
`salary_ripei_profit`            decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_日配定价毛利额',
`salary_bbc_sales_value`         decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_BBC销售额',
`salary_bbc_profit`              decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_BBC定价毛利额',
`salary_ripei_bbc_sales_value`   decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_日配&BBC销售额',
`salary_ripei_bbc_profit`        decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_日配&BBC定价毛利额',
`receivable_amount`              decimal(20,6)        DEFAULT NULL COMMENT    '应收金额',
`overdue_amount`                 decimal(20,6)        DEFAULT NULL COMMENT    '逾期金额',
`salesperson_over_rate`          decimal(20,6)        DEFAULT NULL COMMENT    '逾期系数',
`tc_sales_value`                 decimal(20,6)        DEFAULT NULL COMMENT    '提成_销售额',
`tc_profit`                      decimal(20,6)        DEFAULT NULL COMMENT    '提成_定价毛利额',
`tc_total`                       decimal(20,6)        DEFAULT NULL COMMENT    '总提成',
`create_by`                      varchar(64)          DEFAULT NULL COMMENT    '创建人',
`create_time`                    datetime             DEFAULT NULL COMMENT    '创建时间',
`update_time`                    datetime             DEFAULT NULL COMMENT    '更新时间',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT    '统计日期',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售员提成表';


--客户提成表
CREATE TABLE `report_sss_r_m_crm_customer_commission` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(50)          NOT NULL  COMMENT    '业务主键',
`region_code`                        varchar(16)          not NULL COMMENT    '大区编码',
`region_name`                        varchar(16)          not NULL COMMENT    '大区名称',
`province_code`                      varchar(16)          not NULL COMMENT    '省区编码',
`province_name`                      varchar(16)          not NULL COMMENT    '省区名称',
`city_group_code`                    varchar(16)          not NULL COMMENT    '城市组编码',
`city_group_name`                    varchar(16)          not NULL COMMENT    '城市组名称',
`yearmonth`                          varchar(16)          not NULL COMMENT    '年月',
`customer_id`                        varchar(16)          not NULL COMMENT    '客户ID',
`customer_no`                        varchar(16)          not NULL COMMENT    '客户编号',
`customer_name`                      varchar(16)          not NULL COMMENT    '客户名称',
`sales_id`                           varchar(16)          not NULL COMMENT    '销售员ID',
`work_no`                            varchar(16)          not NULL COMMENT    '销售员工号',
`sales_name`                         varchar(16)          not NULL COMMENT    '销售员名称',
`is_part_time_service_manager`       varchar(16)          DEFAULT NULL COMMENT    '销售员是否兼岗服务管家',
`service_id`                         varchar(16)          DEFAULT NULL COMMENT    '服务管家ID',
`service_work_no`                    varchar(16)          DEFAULT NULL COMMENT    '服务管家工号',
`service_name`                       varchar(16)          DEFAULT NULL COMMENT    '服务管家名称',
`sales_value`                        decimal(20,6)        DEFAULT NULL COMMENT    '销售额',
`ripei_sales_value`                  decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额',
`bbc_sales_value`                    decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额',
`fuli_sales_value`                   decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额',
`ripei_bbc_sales_value`              decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额',
`profit`                             decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额',
`ripei_profit`                       decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额',
`bbc_profit`                         decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额',
`fuli_profit`                        decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额',
`ripei_bbc_profit`                   decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额',
`prorate`                            decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利率',
`ripei_prorate`                      decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利率',
`bbc_prorate`                        decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利率',
`fuli_prorate`                       decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利率',
`ripei_bbc_prorate`                  decimal(20,6)        DEFAULT NULL COMMENT    '日配&bbc定价毛利率',
`salesperson_ripei_bbc_prorate`      decimal(20,6)        DEFAULT NULL COMMENT    '销售员日配&bbc定价毛利率',
`salesperson_fuli_prorate`           decimal(20,6)        DEFAULT NULL COMMENT    '销售员福利定价毛利率',
`salary_fuli_sales_value`            decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_福利销售额',
`salary_fuli_profit`                 decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_福利定价毛利额',
`salary_ripei_sales_value`           decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_日配销售额',
`salary_ripei_profit`                decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_日配定价毛利额',
`salary_bbc_sales_value`             decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_BBC销售额',
`salary_bbc_profit`                  decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_BBC定价毛利额',
`salary_ripei_bbc_sales_value`       decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_日配&BBC销售额',
`salary_ripei_bbc_profit`            decimal(20,6)        DEFAULT NULL COMMENT    '奖金包_日配&BBC定价毛利额',
`receivable_amount`                  decimal(20,6)        DEFAULT NULL COMMENT    '应收金额',
`overdue_amount`                     decimal(20,6)        DEFAULT NULL COMMENT    '逾期金额',
`assigned_type`                      decimal(20,6)        DEFAULT NULL COMMENT    '分配类别',
`salesperson_sales_value_fp_rate`    decimal(20,6)        DEFAULT NULL COMMENT    '销售员销售额分配比例',
`salesperson_profit_fp_rate`         decimal(20,6)        DEFAULT NULL COMMENT    '销售员定价毛利额分配比例',
`service_sales_value_fp_rate`        decimal(20,6)        DEFAULT NULL COMMENT    '服务管家销售额分配比例',
`service_profit_fp_rate`             decimal(20,6)        DEFAULT NULL COMMENT    '服务管家定价毛利额分配比例',
`salesperson_over_rate`              decimal(20,6)        DEFAULT NULL COMMENT    '销售员逾期系数',
`service_over_rate`                  decimal(20,6)        DEFAULT NULL COMMENT    '服务管家逾期系数',
`tc_ripei_sales_value_salesperson`   decimal(20,6)        DEFAULT NULL COMMENT    '提成_销售员_销售额',
`tc_sales_value_service`             decimal(20,6)        DEFAULT NULL COMMENT    '提成_服务管家_销售额',
`tc_ripei_profit_salesperson`        decimal(20,6)        DEFAULT NULL COMMENT    '提成_销售员_定价毛利额',
`tc_profit_service`                  decimal(20,6)        DEFAULT NULL COMMENT    '提成_服务管家_定价毛利额',
`tc_salesperson`                     decimal(20,6)        DEFAULT NULL COMMENT    '提成_销售员',
`tc_service`                         decimal(20,6)        DEFAULT NULL COMMENT    '提成_服务管家',
`create_by`                          varchar(64)          DEFAULT NULL COMMENT    '创建人',
`create_time`                        datetime             DEFAULT NULL COMMENT    '创建时间',
`update_time`                        datetime             DEFAULT NULL COMMENT    '更新时间',
`sdt`                                varchar(64)          DEFAULT NULL COMMENT    '统计日期',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户提成表';


--客户逾期表
CREATE TABLE `report_sss_r_m_crm_customer_over_rate` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(50)          NOT NULL  COMMENT    '业务主键',
`region_code`                    varchar(16)          not NULL COMMENT    '大区编码',
`region_name`                    varchar(16)          not NULL COMMENT    '大区名称',
`province_code`                  varchar(16)          not NULL COMMENT    '省区编码',
`province_name`                  varchar(16)          not NULL COMMENT    '省区名称',
`city_group_code`                varchar(16)          not NULL COMMENT    '城市组编码',
`city_group_name`                varchar(16)          not NULL COMMENT    '城市组名称',
`yearmonth`                      varchar(16)          not NULL COMMENT    '年月',
`channel_code`                   varchar(16)          not NULL COMMENT    '渠道编码',
`channel_name`                   varchar(16)          not NULL COMMENT    '渠道名称',
`customer_id`                    varchar(16)          not NULL COMMENT    '客户ID',
`customer_no`                    varchar(16)          not NULL COMMENT    '客户编号',
`customer_name`                  varchar(16)          not NULL COMMENT    '客户名称',
`sales_id`                       varchar(16)          not NULL COMMENT    '销售员ID',
`work_no`                        varchar(16)          not NULL COMMENT    '销售员工号',
`sales_name`                     varchar(16)          not NULL COMMENT    '销售员名称',
`service_id`                     varchar(16)          not NULL COMMENT    '服务管家ID',
`service_work_no`                varchar(16)          not NULL COMMENT    '服务管家工号',
`service_name`                   varchar(16)          not NULL COMMENT    '服务管家名称',
`is_part_time_service_manager`   varchar(16)          DEFAULT NULL COMMENT    '销售员是否兼岗服务管家',
`payment_terms`                  varchar(16)          DEFAULT NULL COMMENT    '账期类型',
`payment_days`                   int                  DEFAULT NULL COMMENT    '账期天数',
`payment_name`                   varchar(16)          DEFAULT NULL COMMENT    '账期名称',
`company_code`                   varchar(16)          DEFAULT NULL COMMENT    '公司编码',
`company_name`                   varchar(16)          DEFAULT NULL COMMENT    '公司名称',
`receivable_amount`              decimal(20,6)        DEFAULT NULL COMMENT    '应收金额',
`overdue_amount`                 decimal(20,6)        DEFAULT NULL COMMENT    '逾期金额',
`overdue_coefficient_numerator`  decimal(20,6)        DEFAULT NULL COMMENT    '逾期金额*逾期天数',
`overdue_coefficient_denominator`decimal(20,6)        DEFAULT NULL COMMENT    '应收金额*帐期天数',
`over_rate`                      decimal(20,6)        DEFAULT NULL COMMENT    '逾期系数',
`is_greater_0`                   varchar(16)          DEFAULT NULL COMMENT    '应收大于0',
`create_by`                      varchar(64)          DEFAULT NULL COMMENT    '创建人',
`create_time`                    datetime             DEFAULT NULL COMMENT    '创建时间',
`update_time`                    datetime             DEFAULT NULL COMMENT    '更新时间',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT    '统计日期',

  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户逾期表';
