--客户提成信息表-销售员
CREATE TABLE `report_sss_r_m_crm_sales_customer_commission_new` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(64)          NOT NULL  COMMENT    '业务主键',
`customer_no`                    varchar(64)          NOT NULL  COMMENT    '客户编码',
`customer_name`                  varchar(64)          NOT NULL  COMMENT    '客户名称',
`sales_id`                       varchar(64)          NOT NULL  COMMENT    '销售员id',
`work_no`                        varchar(64)          NOT NULL  COMMENT    '销售员工号',
`sales_name`                     varchar(64)          NOT NULL  COMMENT    '销售员名称',
`sales_value`                    decimal(20,6)        DEFAULT NULL COMMENT    '销售额',
`ripei_sales_value`              decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额',
`bbc_sales_value`                decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额',
`ripei_bbc_sales_value`          decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额',
`fuli_sales_value`               decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额',
`sales_value_commion`            decimal(20,6)        DEFAULT NULL COMMENT    '销售额提成',
`ripei_sales_value_commion`      decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额提成',
`bbc_sales_value_commion`        decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额提成',
`ripei_bbc_sales_value_commion`  decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额提成',
`fuli_sales_value_commion`       decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额提成',
`profit`                         decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额',
`ripei_profit`                   decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额',
`bbc_profit`                     decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额',
`ripei_bbc_profit`               decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额',
`fuli_profit`                    decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额',
`profit_commion`                 decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额提成',
`ripei_profit_commion`           decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额提成',
`bbc_profit_commion`             decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额提成',
`ripei_bbc_profit_commion`       decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额提成',
`fuli_profit_commion`            decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额提成',
`prorate`                        decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利率',
`ripei_prorate`                  decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利率',
`bbc_prorate`                    decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利率',
`ripei_bbc_prorate`              decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利率',
`fuli_prorate`                   decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利率',
`commion_total`                  decimal(20,6)        DEFAULT NULL COMMENT    '提成总计',
`ripei_commion_total`            decimal(20,6)        DEFAULT NULL COMMENT    '日配提成总计',
`bbc_commion_total`              decimal(20,6)        DEFAULT NULL COMMENT    'BBC提成总计',
`commion_ripei_bbc_total`        decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC提成总计',
`commion_fuli_total`             decimal(20,6)        DEFAULT NULL COMMENT    '福利提成总计',
`overdue_rate`                   decimal(20,6)        DEFAULT NULL COMMENT    '逾期系数',
`refund_sales_value`             decimal(20,6)        DEFAULT NULL COMMENT    '退货金额',
`ripei_refund_sales_value`       decimal(20,6)        DEFAULT NULL COMMENT    '日配退货金额',
`bbc_refund_sales_value`         decimal(20,6)        DEFAULT NULL COMMENT    'BBC退货金额',
`ripei_bbc_refund_sales_value`   decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC退货金额',
`fuli_refund_sales_value`        decimal(20,6)        DEFAULT NULL COMMENT    '福利退货金额',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT    '同步时间',
`updated_time`                   varchar(64)          DEFAULT NULL COMMENT    '更新时间',
`smonth`						 varchar(64) 		  DEFAULT NULL COMMENT 	  '按年月分区'
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户提成信息表-销售员';


--提成趋势表-销售员
CREATE TABLE `report_sss_r_d_crm_sales_commission_trend_new` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(64)          NOT NULL  COMMENT    '业务主键',
`sales_id`                       varchar(64)          NOT NULL  COMMENT    '销售员id',
`work_no`                        varchar(64)          NOT NULL  COMMENT    '销售员工号',
`sales_name`                     varchar(64)          NOT NULL  COMMENT    '销售员名称',
`sales_date`                     varchar(64)          DEFAULT NULL COMMENT    '销售日期',
`sales_value_commion`            decimal(20,6)        DEFAULT NULL COMMENT    '销售额提成',
`ripei_sales_value_commion`      decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额提成',
`bbc_sales_value_commion`        decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额提成',
`ripei_bbc_sales_value_commion`  decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额提成',
`fuli_sales_value_commion`       decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额提成',
`profit_commion`                 decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额提成',
`ripei_profit_commion`           decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额提成',
`bbc_profit_commion`             decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额提成',
`ripei_bbc_profit_commion`       decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额提成',
`fuli_profit_commion`            decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额提成',
`commion_total`                  decimal(20,6)        DEFAULT NULL COMMENT    '提成总计',
`ripei_commion_total`            decimal(20,6)        DEFAULT NULL COMMENT    '日配提成总计',
`bbc_commion_total`              decimal(20,6)        DEFAULT NULL COMMENT    'BBC提成总计',
`commion_ripei_bbc_total`        decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC提成总计',
`commion_fuli_total`             decimal(20,6)        DEFAULT NULL COMMENT    '福利提成总计',
`smonth`                         varchar(64)          DEFAULT NULL COMMENT    '年月',
`updated_time`                   varchar(64)          DEFAULT NULL COMMENT    '更新时间',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT    '提成日期分区'
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='提成趋势表-销售员';


--销售趋势表-销售员
CREATE TABLE `report_sss_r_d_crm_sales_sale_trend_new` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(64)          NOT NULL  COMMENT    '业务主键',
`sales_id`                       varchar(64)          NOT NULL  COMMENT    '销售员id',
`work_no`                        varchar(64)          NOT NULL  COMMENT    '销售员工号',
`sales_name`                     varchar(64)          NOT NULL  COMMENT    '销售员名称',
`sales_date`                     varchar(64)          DEFAULT NULL COMMENT    '销售日期',
`sales_value`                    decimal(20,6)        DEFAULT NULL COMMENT    '销售额',
`ripei_sales_value`              decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额',
`bbc_sales_value`                decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额',
`ripei_bbc_sales_value`          decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额',
`fuli_sales_value`               decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额',
`profit`                         decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额',
`ripei_profit`                   decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额',
`bbc_profit`                     decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额',
`ripei_bbc_profit`               decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额',
`fuli_profit`                    decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额',
`refund_sales_value`             decimal(20,6)        DEFAULT NULL COMMENT    '退货金额',
`ripei_refund_sales_value`       decimal(20,6)        DEFAULT NULL COMMENT    '日配退货金额',
`bbc_refund_sales_value`         decimal(20,6)        DEFAULT NULL COMMENT    'BBC退货金额',
`ripei_bbc_refund_sales_value`   decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC退货金额',
`fuli_refund_sales_value`        decimal(20,6)        DEFAULT NULL COMMENT    '福利退货金额',
`smonth`                         varchar(64)          DEFAULT NULL COMMENT    '年月',
`updated_time`                   varchar(64)          DEFAULT NULL COMMENT    '更新时间',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT    '销售日期分区'
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售趋势表';


--客户提成信息表-服务管家
CREATE TABLE `report_sss_r_m_crm_service_customer_commission_new` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(64)          NOT NULL  COMMENT    '业务主键',
`customer_no`                    varchar(64)          NOT NULL  COMMENT    '客户编码',
`customer_name`                  varchar(64)          NOT NULL  COMMENT    '客户名称',
`service_id`                     varchar(64)          NOT NULL  COMMENT    '服务管家id',
`service_work_no`                varchar(64)          DEFAULT NULL COMMENT    '服务管家工号',
`service_name`                   varchar(64)          DEFAULT NULL COMMENT    '服务管家名称',
`sales_value`                    decimal(20,6)        DEFAULT NULL COMMENT    '销售额',
`ripei_sales_value`              decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额',
`bbc_sales_value`                decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额',
`ripei_bbc_sales_value`          decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额',
`fuli_sales_value`               decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额',
`sales_value_commion`            decimal(20,6)        DEFAULT NULL COMMENT    '销售额提成',
`ripei_sales_value_commion`      decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额提成',
`bbc_sales_value_commion`        decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额提成',
`ripei_bbc_sales_value_commion`  decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额提成',
`fuli_sales_value_commion`       decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额提成',
`profit`                         decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额',
`ripei_profit`                   decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额',
`bbc_profit`                     decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额',
`ripei_bbc_profit`               decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额',
`fuli_profit`                    decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额',
`profit_commion`                 decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额提成',
`ripei_profit_commion`           decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额提成',
`bbc_profit_commion`             decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额提成',
`ripei_bbc_profit_commion`       decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额提成',
`fuli_profit_commion`            decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额提成',
`prorate`                        decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利率',
`ripei_prorate`                  decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利率',
`bbc_prorate`                    decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利率',
`ripei_bbc_prorate`              decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利率',
`fuli_prorate`                   decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利率',
`commion_total`                  decimal(20,6)        DEFAULT NULL COMMENT    '提成总计',
`ripei_commion_total`            decimal(20,6)        DEFAULT NULL COMMENT    '日配提成总计',
`bbc_commion_total`              decimal(20,6)        DEFAULT NULL COMMENT    'BBC提成总计',
`commion_ripei_bbc_total`        decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC提成总计',
`commion_fuli_total`             decimal(20,6)        DEFAULT NULL COMMENT    '福利提成总计',
`overdue_rate`                   decimal(20,6)        DEFAULT NULL COMMENT    '逾期系数',
`refund_sales_value`             decimal(20,6)        DEFAULT NULL COMMENT    '退货金额',
`ripei_refund_sales_value`       decimal(20,6)        DEFAULT NULL COMMENT    '日配退货金额',
`bbc_refund_sales_value`         decimal(20,6)        DEFAULT NULL COMMENT    'BBC退货金额',
`ripei_bbc_refund_sales_value`   decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC退货金额',
`fuli_refund_sales_value`        decimal(20,6)        DEFAULT NULL COMMENT    '福利退货金额',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT    '同步时间',
`updated_time`                   varchar(64)          DEFAULT NULL COMMENT    '更新时间',
`smonth`						 varchar(64) 		  DEFAULT NULL COMMENT 	  '按年月分区'
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户提成信息表-服务管家';


--提成趋势表-服务管家
CREATE TABLE `report_sss_r_d_crm_service_commission_trend_new` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(64)          NOT NULL  COMMENT    '业务主键',
`service_id`                     varchar(64)          NOT NULL  COMMENT    '服务管家id',
`service_work_no`                varchar(64)          NOT NULL  COMMENT    '服务管家工号',
`service_name`                   varchar(64)          NOT NULL  COMMENT    '服务管家名称',
`sales_date`                     varchar(64)          DEFAULT NULL COMMENT    '销售日期',
`sales_value_commion`            decimal(20,6)        DEFAULT NULL COMMENT    '销售额提成',
`ripei_sales_value_commion`      decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额提成',
`bbc_sales_value_commion`        decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额提成',
`ripei_bbc_sales_value_commion`  decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额提成',
`fuli_sales_value_commion`       decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额提成',
`profit_commion`                 decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额提成',
`ripei_profit_commion`           decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额提成',
`bbc_profit_commion`             decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额提成',
`ripei_bbc_profit_commion`       decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额提成',
`fuli_profit_commion`            decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额提成',
`commion_total`                  decimal(20,6)        DEFAULT NULL COMMENT    '提成总计',
`ripei_commion_total`            decimal(20,6)        DEFAULT NULL COMMENT    '日配提成总计',
`bbc_commion_total`              decimal(20,6)        DEFAULT NULL COMMENT    'BBC提成总计',
`commion_ripei_bbc_total`        decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC提成总计',
`commion_fuli_total`             decimal(20,6)        DEFAULT NULL COMMENT    '福利提成总计',
`smonth`                         varchar(64)          DEFAULT NULL COMMENT    '年月',
`updated_time`                   varchar(64)          DEFAULT NULL COMMENT    '更新时间',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT    '提成日期分区'
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='提成趋势表-服务管家';


--销售趋势表-服务管家
CREATE TABLE `report_sss_r_d_crm_service_sale_trend_new` (
`id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`biz_id`                         varchar(64)          NOT NULL  COMMENT    '业务主键',
`service_id`                     varchar(64)          NOT NULL  COMMENT    '服务管家id',
`service_work_no`                varchar(64)          NOT NULL  COMMENT    '服务管家工号',
`service_name`                   varchar(64)          NOT NULL  COMMENT    '服务管家名称',
`sales_date`                     varchar(64)          DEFAULT NULL COMMENT    '销售日期',
`sales_value`                    decimal(20,6)        DEFAULT NULL COMMENT    '销售额',
`ripei_sales_value`              decimal(20,6)        DEFAULT NULL COMMENT    '日配销售额',
`bbc_sales_value`                decimal(20,6)        DEFAULT NULL COMMENT    'BBC销售额',
`ripei_bbc_sales_value`          decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC销售额',
`fuli_sales_value`               decimal(20,6)        DEFAULT NULL COMMENT    '福利销售额',
`profit`                         decimal(20,6)        DEFAULT NULL COMMENT    '定价毛利额',
`ripei_profit`                   decimal(20,6)        DEFAULT NULL COMMENT    '日配定价毛利额',
`bbc_profit`                     decimal(20,6)        DEFAULT NULL COMMENT    'BBC定价毛利额',
`ripei_bbc_profit`               decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC定价毛利额',
`fuli_profit`                    decimal(20,6)        DEFAULT NULL COMMENT    '福利定价毛利额',
`refund_sales_value`             decimal(20,6)        DEFAULT NULL COMMENT    '退货金额',
`ripei_refund_sales_value`       decimal(20,6)        DEFAULT NULL COMMENT    '日配退货金额',
`bbc_refund_sales_value`         decimal(20,6)        DEFAULT NULL COMMENT    'BBC退货金额',
`ripei_bbc_refund_sales_value`   decimal(20,6)        DEFAULT NULL COMMENT    '日配&BBC退货金额',
`fuli_refund_sales_value`        decimal(20,6)        DEFAULT NULL COMMENT    '福利退货金额',
`smonth`                         varchar(64)          DEFAULT NULL COMMENT    '年月',
`updated_time`                   varchar(64)          DEFAULT NULL COMMENT    '更新时间',
`sdt`                            varchar(64)          DEFAULT NULL COMMENT    '销售日期分区'
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售趋势表';
